// Phase 8: product variants for the buyer to choose from.
//
// Image hosting: real product images hotlinked from manufacturer / retailer websites.
// These are public CDN URLs brands publish for product listings. OfficeKit links to
// them as a comparison-shopping site (analogous to PriceRunner / Prisjakt / Google
// Shopping). If a brand URL 404s at runtime the UI falls back to /variants/_placeholder.svg
// via an onError handler on every <img>.
//
// Prices are in SEK (converted to öre at seed time, ×100).

export interface SeedVariant {
  id: string;                           // human-readable slug for the variant
  itemId: string;                       // FK to ItemCatalog.id
  name: string;
  manufacturer: string;
  sku?: string;
  imageUrl: string;
  specs: Record<string, string>;
  priceNewSek: number;
  priceUsedDefaultSek?: number;
  manufacturerUrl?: string;
  blocketSearchQuery?: string;
  traderaSearchQuery?: string;
  displayOrder: number;
}


export const VARIANTS: SeedVariant[] = [
  // ---- desk-electric (4) ----
  { id: "desk-electric-kinnarps-oberon", itemId: "desk-electric", name: "Oberon sit-stand desk", manufacturer: "Kinnarps", sku: "OBERON-160", imageUrl: "https://www.kinnarps.com/49d4ed/globalassets/products/desks/oberon/oberon-pic1.jpg", specs: { size: "160×80 cm", height: "65-130 cm", memory: "4 positions", finish: "Oak laminate" }, priceNewSek: 7200, priceUsedDefaultSek: 3400, manufacturerUrl: "https://www.kinnarps.com", blocketSearchQuery: "Kinnarps Oberon sit-stand 160", traderaSearchQuery: "Kinnarps Oberon hojhojsbord", displayOrder: 0 },
  { id: "desk-electric-ikea-bekant", itemId: "desk-electric", name: "Bekant sit-stand desk", manufacturer: "IKEA Business", sku: "BEKANT-160", imageUrl: "https://www.ikea.com/se/sv/images/products/bekant-skrivbord-sitt-staa-vit__0825166_pe698863_s5.jpg", specs: { size: "160×80 cm", height: "65-125 cm", memory: "none", finish: "White" }, priceNewSek: 4900, priceUsedDefaultSek: 2200, manufacturerUrl: "https://www.ikea.com/se/sv", blocketSearchQuery: "IKEA Bekant 160 hojhojsbord", traderaSearchQuery: "IKEA Bekant hojhojsbord", displayOrder: 1 },
  { id: "desk-electric-flexispot-e7", itemId: "desk-electric", name: "E7 sit-stand desk", manufacturer: "FlexiSpot", sku: "E7-160", imageUrl: "https://flexispot.se/cdn/shop/files/E7_Black_2_d22055d8.jpg", specs: { size: "160×80 cm", height: "60-125 cm", memory: "4 positions", finish: "Bamboo" }, priceNewSek: 5800, priceUsedDefaultSek: 2900, manufacturerUrl: "https://flexispot.se", blocketSearchQuery: "FlexiSpot E7 hojhojsbord", traderaSearchQuery: "FlexiSpot hojhojsbord", displayOrder: 2 },
  { id: "desk-electric-uplift-v2", itemId: "desk-electric", name: "V2 sit-stand desk", manufacturer: "UPLIFT", sku: "UPLIFT-V2-72", imageUrl: "https://www.upliftdesk.com/cdn/shop/products/v2-commercial-standing-desk-uplift-desk.jpg", specs: { size: "180×75 cm", height: "65-130 cm", memory: "4 positions", finish: "Walnut" }, priceNewSek: 9800, priceUsedDefaultSek: 4900, manufacturerUrl: "https://upliftdesk.com", blocketSearchQuery: "UPLIFT V2 hojhojsbord", traderaSearchQuery: "UPLIFT skrivbord", displayOrder: 3 },

  // ---- task-chair (4) ----
  { id: "task-chair-rh-logic", itemId: "task-chair", name: "Logic 400", manufacturer: "RH", sku: "RH-LOGIC-400", imageUrl: "https://www.rh.se/contentassets/4d4f7ad8676b40c4a3b07a4e6cb8de40/rh-logic-400-stol.jpg", specs: { recline: "synchron tilt", lumbar: "adjustable", armrests: "4D", warranty: "10 years" }, priceNewSek: 8500, priceUsedDefaultSek: 3800, manufacturerUrl: "https://www.rh.se", blocketSearchQuery: "RH Logic 400 kontorsstol", traderaSearchQuery: "RH Logic kontorsstol", displayOrder: 0 },
  { id: "task-chair-aeron", itemId: "task-chair", name: "Aeron Chair (size B)", manufacturer: "Herman Miller", sku: "AERON-B", imageUrl: "https://store.hermanmiller.com/on/demandware.static/-/Sites-master-catalog_HMI/default/dw9d091cf1/images/lifestyle/AER_BB_BBBK_BK_BK_BK_BB_AJ_BB_LF_2C.jpg", specs: { recline: "tilt limiter", lumbar: "PostureFit", armrests: "4D adjustable", warranty: "12 years" }, priceNewSek: 18500, priceUsedDefaultSek: 7900, manufacturerUrl: "https://www.hermanmiller.com", blocketSearchQuery: "Herman Miller Aeron storlek B", traderaSearchQuery: "Herman Miller Aeron", displayOrder: 1 },
  { id: "task-chair-markus", itemId: "task-chair", name: "Markus", manufacturer: "IKEA", sku: "MARKUS", imageUrl: "https://www.ikea.com/se/sv/images/products/markus-kontorsstol-vissle-moerkgraa__0724714_pe734597_s5.jpg", specs: { recline: "tilt", lumbar: "fixed", armrests: "fixed", warranty: "10 years" }, priceNewSek: 2495, priceUsedDefaultSek: 990, manufacturerUrl: "https://www.ikea.com/se/sv/p/markus-kontorsstol-vissle-moerkgraa-70261150/", blocketSearchQuery: "IKEA Markus kontorsstol", traderaSearchQuery: "IKEA Markus stol", displayOrder: 2 },
  { id: "task-chair-steelcase-leap", itemId: "task-chair", name: "Leap V2", manufacturer: "Steelcase", sku: "LEAP-V2", imageUrl: "https://www.steelcase.com/content/uploads/2018/01/Leap-Cogent-Connect-Aqua_HR.jpg", specs: { recline: "LiveBack", lumbar: "adjustable", armrests: "4D", warranty: "12 years" }, priceNewSek: 14500, priceUsedDefaultSek: 5500, manufacturerUrl: "https://www.steelcase.com", blocketSearchQuery: "Steelcase Leap V2", traderaSearchQuery: "Steelcase Leap", displayOrder: 3 },

  // ---- monitor-27 (4) ----
  { id: "monitor-27-dell-u2723qe", itemId: "monitor-27", name: 'UltraSharp 27" 4K U2723QE', manufacturer: "Dell", sku: "U2723QE", imageUrl: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/peripherals/monitors/u-series/u2723qe/global-spi/u2723qe-cfp-00010-bk-gy-1.png", specs: { resolution: "3840×2160", panel: "IPS Black", refresh: "60 Hz", ports: "USB-C 90W, DP, HDMI" }, priceNewSek: 6900, priceUsedDefaultSek: 3200, manufacturerUrl: "https://www.dell.com", blocketSearchQuery: "Dell UltraSharp U2723QE", traderaSearchQuery: "Dell U2723QE", displayOrder: 0 },
  { id: "monitor-27-lg-27up850", itemId: "monitor-27", name: '27" UHD 27UP850N-W', manufacturer: "LG", sku: "27UP850N-W", imageUrl: "https://www.lg.com/us/images/monitors/md08000164/gallery/D-3.jpg", specs: { resolution: "3840×2160", panel: "IPS", refresh: "60 Hz", ports: "USB-C 96W, DP, 2× HDMI" }, priceNewSek: 5900, priceUsedDefaultSek: 2800, manufacturerUrl: "https://www.lg.com/se", blocketSearchQuery: "LG 27UP850 27 4K", traderaSearchQuery: "LG 27UP850", displayOrder: 1 },
  { id: "monitor-27-benq-pd2700u", itemId: "monitor-27", name: 'DesignVue PD2700U', manufacturer: "BenQ", sku: "PD2700U", imageUrl: "https://image.benq.com/is/image/benqco/pd2700u-fy20-front?$ResponsivePreset$", specs: { resolution: "3840×2160", panel: "IPS", refresh: "60 Hz", ports: "DP, 2× HDMI, USB-A hub" }, priceNewSek: 7200, priceUsedDefaultSek: 3400, manufacturerUrl: "https://www.benq.eu", blocketSearchQuery: "BenQ PD2700U 27", traderaSearchQuery: "BenQ PD2700U", displayOrder: 2 },
  { id: "monitor-27-samsung-s27a800", itemId: "monitor-27", name: 'ViewFinity S8 S27A800UJN', manufacturer: "Samsung", sku: "S27A800UJN", imageUrl: "https://images.samsung.com/is/image/samsung/p6pim/se/ls27a800nmpxen/gallery/se-viewfinity-s8-s60ua-ls27a800nmpxen-531203569", specs: { resolution: "3840×2160", panel: "IPS", refresh: "60 Hz", ports: "USB-C 90W, DP, HDMI" }, priceNewSek: 5400, priceUsedDefaultSek: 2500, manufacturerUrl: "https://www.samsung.com/se", blocketSearchQuery: "Samsung S27A800 27 4K", traderaSearchQuery: "Samsung ViewFinity", displayOrder: 3 },

  // ---- monitor-arm (3) ----
  { id: "monitor-arm-ergotron-lx", itemId: "monitor-arm", name: "LX Desk Mount LCD Arm", manufacturer: "Ergotron", sku: "LX-DESK", imageUrl: "https://www.ergotron.com/Portals/0/literature/productSheets/english/lx-desk-mount-lcd-arm.jpg", specs: { mount: "VESA 75/100", capacity: "up to 11.3 kg", motion: "tilt, pan, rotate" }, priceNewSek: 2400, priceUsedDefaultSek: 1100, manufacturerUrl: "https://www.ergotron.com", blocketSearchQuery: "Ergotron LX skarmarm", traderaSearchQuery: "Ergotron LX", displayOrder: 0 },
  { id: "monitor-arm-humanscale-m8", itemId: "monitor-arm", name: "M8.1 Monitor Arm", manufacturer: "Humanscale", sku: "M8.1", imageUrl: "https://www.humanscale.com/static/upload/m81-product.jpg", specs: { mount: "VESA 75/100", capacity: "up to 13 kg", motion: "weightless counterbalance" }, priceNewSek: 4200, priceUsedDefaultSek: 2000, manufacturerUrl: "https://www.humanscale.com", blocketSearchQuery: "Humanscale M8 skarmarm", traderaSearchQuery: "Humanscale M8", displayOrder: 1 },
  { id: "monitor-arm-ikea-elloven", itemId: "monitor-arm", name: "Elloven", manufacturer: "IKEA", sku: "ELLOVEN", imageUrl: "https://www.ikea.com/se/sv/images/products/elloven-monitorstativ-vit__0911935_pe781073_s5.jpg", specs: { mount: "VESA 100", capacity: "up to 8 kg", motion: "tilt, swivel" }, priceNewSek: 599, priceUsedDefaultSek: 250, manufacturerUrl: "https://www.ikea.com/se/sv", blocketSearchQuery: "IKEA Elloven skarmarm", traderaSearchQuery: "IKEA Elloven", displayOrder: 2 },

  // ---- headset (3) ----
  { id: "headset-jabra-evolve2-65", itemId: "headset", name: "Evolve2 65 USB-C UC", manufacturer: "Jabra", sku: "EVOLVE2-65-USC", imageUrl: "https://www.jabra.com.cn/-/media/aem/jabra/jabra-product-evolve2-65-uc-stereo-black-hero.jpg", specs: { wireless: "Bluetooth 5.0", battery: "37h talk", noise: "ANC", certs: "Teams/Zoom" }, priceNewSek: 2890, priceUsedDefaultSek: 1300, manufacturerUrl: "https://www.jabra.se", blocketSearchQuery: "Jabra Evolve2 65", traderaSearchQuery: "Jabra Evolve2", displayOrder: 0 },
  { id: "headset-logitech-zone-vibe", itemId: "headset", name: "Zone Vibe 125", manufacturer: "Logitech", sku: "ZONE-VIBE-125", imageUrl: "https://resource.logitech.com/w_692,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/logitech/en/products/headsets/zone-vibe-125/gallery/zone-vibe-125-graphite-gallery-1.png", specs: { wireless: "Bluetooth", battery: "18h", noise: "noise-cancelling mic", certs: "Teams" }, priceNewSek: 1190, priceUsedDefaultSek: 550, manufacturerUrl: "https://www.logitech.com/sv-se", blocketSearchQuery: "Logitech Zone Vibe 125", traderaSearchQuery: "Logitech Zone", displayOrder: 1 },
  { id: "headset-poly-voyager-focus2", itemId: "headset", name: "Voyager Focus 2", manufacturer: "Poly (HP)", sku: "VOYAGER-FOCUS-2", imageUrl: "https://www.poly.com/content/dam/www/products/headsets/voyager/voyager-focus-2/gallery/voyager-focus-2-uc-hero.png", specs: { wireless: "Bluetooth 5.1", battery: "19h talk", noise: "ANC", certs: "Teams/Zoom" }, priceNewSek: 2790, priceUsedDefaultSek: 1300, manufacturerUrl: "https://www.poly.com", blocketSearchQuery: "Poly Voyager Focus 2", traderaSearchQuery: "Poly Voyager", displayOrder: 2 },

  // ---- meeting-table-6 (3) ----
  { id: "meeting-table-6-vitra-em", itemId: "meeting-table-6", name: "EM Table 200×100", manufacturer: "Vitra", sku: "EM-200", imageUrl: "https://www.vitra.com/resource/image/40226/landscape_ratio4x3/1240/930/24f2c1e0e8a0d96bf1d92e0ab3ad0c80/EM/em-table-prouve.jpg", specs: { size: "200×100 cm", finish: "Solid oak", base: "Black powder-coated steel" }, priceNewSek: 18000, priceUsedDefaultSek: 8500, manufacturerUrl: "https://www.vitra.com", blocketSearchQuery: "Vitra EM Table mötesbord", traderaSearchQuery: "Vitra EM Table", displayOrder: 0 },
  { id: "meeting-table-6-string", itemId: "meeting-table-6", name: "Bordsskiva ek 200×100", manufacturer: "String Furniture", sku: "STR-200", imageUrl: "https://www.stringfurniture.com/cdn/shop/files/string-works-meeting-table.jpg", specs: { size: "200×100 cm", finish: "Oak veneer", base: "Anthracite frame" }, priceNewSek: 9500, priceUsedDefaultSek: 4500, manufacturerUrl: "https://stringfurniture.com", blocketSearchQuery: "String mötesbord 200", traderaSearchQuery: "String bord 200", displayOrder: 1 },
  { id: "meeting-table-6-ikea-mittzon", itemId: "meeting-table-6", name: "Mittzon 200×100", manufacturer: "IKEA Business", sku: "MITTZON-200", imageUrl: "https://www.ikea.com/se/sv/images/products/mittzon-konferensbord-fanerad-yta-bjoerk-svart__1140183_pe896128_s5.jpg", specs: { size: "200×100 cm", finish: "White or oak", base: "Steel" }, priceNewSek: 6900, priceUsedDefaultSek: 3000, manufacturerUrl: "https://www.ikea.com/se/sv/cat/mittzon", blocketSearchQuery: "IKEA Mittzon mötesbord", traderaSearchQuery: "IKEA Mittzon", displayOrder: 2 },

  // ---- phone-booth (3) ----
  { id: "phone-booth-framery-one", itemId: "phone-booth", name: "Framery One", manufacturer: "Framery", sku: "FRAMERY-ONE", imageUrl: "https://frameryacoustics.com/wp-content/uploads/2023/05/Framery-One-product.jpg", specs: { capacity: "1 person", ventilation: "active, sensor-triggered", acoustics: "−30 dB", dimensions: "100×90×223 cm" }, priceNewSek: 65000, priceUsedDefaultSek: 28000, manufacturerUrl: "https://frameryacoustics.com", blocketSearchQuery: "Framery One telefonbås", traderaSearchQuery: "Framery telefonbås", displayOrder: 0 },
  { id: "phone-booth-loop-mini", itemId: "phone-booth", name: "Mini Pod", manufacturer: "Loop Phone Booths", sku: "LOOP-MINI", imageUrl: "https://loopphonebooths.com/wp-content/uploads/2021/06/loop-mini-phone-booth-product.jpg", specs: { capacity: "1 person", ventilation: "passive + USB fan", acoustics: "−25 dB", dimensions: "90×90×210 cm" }, priceNewSek: 38000, priceUsedDefaultSek: 18000, manufacturerUrl: "https://loopphonebooths.com", blocketSearchQuery: "Loop telefonbås", traderaSearchQuery: "Loop telefonbås", displayOrder: 1 },
  { id: "phone-booth-zenbooth-solo", itemId: "phone-booth", name: "Solo", manufacturer: "Zenbooth", sku: "SOLO", imageUrl: "https://zenbooth.net/cdn/shop/files/Solo-Zenbooth-Office-Phone-Booth_2000x.jpg", specs: { capacity: "1 person", ventilation: "active", acoustics: "−28 dB", dimensions: "97×97×218 cm" }, priceNewSek: 52000, priceUsedDefaultSek: 24000, manufacturerUrl: "https://zenbooth.net", blocketSearchQuery: "Zenbooth Solo telefonbås", traderaSearchQuery: "Zenbooth", displayOrder: 2 },

  // ---- coffee-machine (3) ----
  { id: "coffee-jura-x8", itemId: "coffee-machine", name: "X8", manufacturer: "Jura", sku: "JURA-X8", imageUrl: "https://www.jura.com/-/media/global/images/home-products/machines/x8/x8-platinum.png", specs: { type: "fully automatic", capacity: "30+ cups/day", milk: "automatic frother" }, priceNewSek: 38000, priceUsedDefaultSek: 16000, manufacturerUrl: "https://se.jura.com", blocketSearchQuery: "Jura X8 espressomaskin", traderaSearchQuery: "Jura X8", displayOrder: 0 },
  { id: "coffee-wmf-9000s", itemId: "coffee-machine", name: "9000 S+", manufacturer: "WMF", sku: "WMF-9000S", imageUrl: "https://www.wmf-coffeemachines.com/medias/9000s-front.png", specs: { type: "fully automatic", capacity: "150+ cups/day", milk: "twin steam" }, priceNewSek: 95000, priceUsedDefaultSek: 45000, manufacturerUrl: "https://www.wmf-coffeemachines.com", blocketSearchQuery: "WMF 9000 kaffemaskin", traderaSearchQuery: "WMF 9000", displayOrder: 1 },
  { id: "coffee-sage-barista-pro", itemId: "coffee-machine", name: "Barista Pro", manufacturer: "Sage", sku: "SES878", imageUrl: "https://www.sageappliances.com/content/dam/sageappliances/eu/en/products/espresso/ses878/page-content/ses878bss-1.jpg", specs: { type: "semi-automatic", capacity: "20 cups/day", milk: "steam wand" }, priceNewSek: 11900, priceUsedDefaultSek: 5500, manufacturerUrl: "https://www.sageappliances.com", blocketSearchQuery: "Sage Barista Pro", traderaSearchQuery: "Sage Barista Pro", displayOrder: 2 },

  // ---- sofa-3 (3) ----
  { id: "sofa-3-vimle", itemId: "sofa-3", name: "Vimle 3-seat", manufacturer: "IKEA", sku: "VIMLE-3", imageUrl: "https://www.ikea.com/se/sv/images/products/vimle-3-sits-soffa-gunnared-beige__0509718_pe635155_s5.jpg", specs: { material: "Gunnared beige fabric", washable: "covers removable", warranty: "10 years" }, priceNewSek: 7995, priceUsedDefaultSek: 3500, manufacturerUrl: "https://www.ikea.com/se/sv/cat/vimle", blocketSearchQuery: "IKEA Vimle 3-sits soffa", traderaSearchQuery: "IKEA Vimle", displayOrder: 0 },
  { id: "sofa-3-stockholm", itemId: "sofa-3", name: "Stockholm 3-seat leather", manufacturer: "IKEA", sku: "STOCKHOLM-3-LTH", imageUrl: "https://www.ikea.com/se/sv/images/products/stockholm-3-sits-soffa-grann-natur__1009376_pe829551_s5.jpg", specs: { material: "Grann nature leather", warranty: "10 years" }, priceNewSek: 15995, priceUsedDefaultSek: 7000, manufacturerUrl: "https://www.ikea.com/se/sv/cat/stockholm", blocketSearchQuery: "IKEA Stockholm soffa läder", traderaSearchQuery: "IKEA Stockholm soffa", displayOrder: 1 },
  { id: "sofa-3-svenssons", itemId: "sofa-3", name: "Borås 3-seat", manufacturer: "Svenssons", sku: "BORAS-3", imageUrl: "https://www.svenssons.se/cdn/shop/files/Boras-3-sits-soffa.jpg", specs: { material: "Velvet, multiple colours", warranty: "5 years" }, priceNewSek: 12500, priceUsedDefaultSek: 5500, manufacturerUrl: "https://www.svenssons.se", blocketSearchQuery: "Borås 3-sits soffa", traderaSearchQuery: "soffa 3-sits", displayOrder: 2 },

  // ---- armchair (3) ----
  { id: "armchair-strandmon", itemId: "armchair", name: "Strandmon Wing Chair", manufacturer: "IKEA", sku: "STRANDMON", imageUrl: "https://www.ikea.com/se/sv/images/products/strandmon-faetoelj-skiftebo-blaa__0837557_pe601478_s5.jpg", specs: { style: "wing chair", material: "Skiftebo dark blue", warranty: "10 years" }, priceNewSek: 4495, priceUsedDefaultSek: 2000, manufacturerUrl: "https://www.ikea.com/se/sv/cat/strandmon", blocketSearchQuery: "IKEA Strandmon fåtölj", traderaSearchQuery: "Strandmon fåtölj", displayOrder: 0 },
  { id: "armchair-eames-lounge", itemId: "armchair", name: "Eames Lounge Chair", manufacturer: "Herman Miller / Vitra", sku: "EAMES-LOUNGE", imageUrl: "https://www.vitra.com/resource/image/40240/landscape_ratio4x3/1240/930/abf12d3b4f9f0e5e9c1bf5e7f3a8d29c/EM/lounge-chair-walnut.jpg", specs: { style: "iconic lounge", material: "Palisander + black leather", warranty: "30 years frame" }, priceNewSek: 78000, priceUsedDefaultSek: 38000, manufacturerUrl: "https://www.vitra.com", blocketSearchQuery: "Eames Lounge Chair Vitra", traderaSearchQuery: "Eames Lounge", displayOrder: 1 },
  { id: "armchair-poaeng", itemId: "armchair", name: "Poäng", manufacturer: "IKEA", sku: "POAEG", imageUrl: "https://www.ikea.com/se/sv/images/products/poaeng-faetoelj-bjoerkfaner-hillared-antracit__0571538_pe666933_s5.jpg", specs: { style: "bent birch frame", material: "Hillared anthracite", warranty: "10 years" }, priceNewSek: 1495, priceUsedDefaultSek: 650, manufacturerUrl: "https://www.ikea.com/se/sv/cat/poaeg", blocketSearchQuery: "IKEA Poäng fåtölj", traderaSearchQuery: "IKEA Poäng", displayOrder: 2 },

  // ---- locker-8 (3) ----
  { id: "locker-8-bisley", itemId: "locker-8", name: "MultiDrawer 8-locker steel", manufacturer: "Bisley", sku: "BISLEY-8", imageUrl: "https://bisley.com/wp-content/uploads/2023/05/Bisley-Multidrawer-A4-locker.jpg", specs: { compartments: "8", locks: "key per compartment", finish: "Slate gray" }, priceNewSek: 7200, priceUsedDefaultSek: 3200, manufacturerUrl: "https://bisley.com", blocketSearchQuery: "Bisley 8 fack stållskåp", traderaSearchQuery: "Bisley", displayOrder: 0 },
  { id: "locker-8-trippstadius", itemId: "locker-8", name: "TS8 lockers", manufacturer: "Tripps & Stadius", sku: "TS8", imageUrl: "https://www.ikea.com/se/sv/images/products/trotten-skap-med-laasbar-doerr-antracit__0931996_pe790871_s5.jpg", specs: { compartments: "8", locks: "digital or key", finish: "Powder coat, RAL options" }, priceNewSek: 8400, priceUsedDefaultSek: 3700, manufacturerUrl: "#", blocketSearchQuery: "kontorsskap 8 fack", traderaSearchQuery: "kontorsskap låsbart", displayOrder: 1 },
  { id: "locker-8-ikea-trotten", itemId: "locker-8", name: "Trotten 8-compartment", manufacturer: "IKEA Business", sku: "TROTTEN-8", imageUrl: "https://www.ikea.com/se/sv/images/products/trotten-skap-med-laasbar-doerr-antracit__0931996_pe790871_s5.jpg", specs: { compartments: "8", locks: "key per compartment", finish: "Anthracite" }, priceNewSek: 4995, priceUsedDefaultSek: 2200, manufacturerUrl: "https://www.ikea.com/se/sv", blocketSearchQuery: "IKEA Trotten 8 fack", traderaSearchQuery: "IKEA Trotten", displayOrder: 2 },

  // ---- whiteboard (3) ----
  { id: "whiteboard-lintex", itemId: "whiteboard", name: "Air Whiteboard 200×100", manufacturer: "Lintex", sku: "LINTEX-AIR-200", imageUrl: "https://lintex.com/wp-content/uploads/2022/02/Air-whiteboard-product.jpg", specs: { size: "200×100 cm", surface: "enamel", magnetic: "yes" }, priceNewSek: 3200, priceUsedDefaultSek: 1400, manufacturerUrl: "https://lintex.com", blocketSearchQuery: "Lintex whiteboard 200", traderaSearchQuery: "Lintex whiteboard", displayOrder: 0 },
  { id: "whiteboard-naga", itemId: "whiteboard", name: "Classic Whiteboard 200×100", manufacturer: "NAGA", sku: "NAGA-200", imageUrl: "https://naga.dk/media/catalog/product/cache/whiteboard-classic-200x100.jpg", specs: { size: "200×100 cm", surface: "lacquered steel", magnetic: "yes" }, priceNewSek: 1990, priceUsedDefaultSek: 800, manufacturerUrl: "https://naga.dk", blocketSearchQuery: "NAGA whiteboard 200", traderaSearchQuery: "whiteboard 200", displayOrder: 1 },
  { id: "whiteboard-rocada-mobile", itemId: "whiteboard", name: "Mobile whiteboard 200×100", manufacturer: "Rocada", sku: "RD-MOBILE-200", imageUrl: "https://www.rocada.es/wp-content/uploads/2020/mobile-whiteboard-product.jpg", specs: { size: "200×100 cm", surface: "magnetic enamel", mobile: "wheels, double-sided" }, priceNewSek: 4500, priceUsedDefaultSek: 1900, manufacturerUrl: "https://rocada.es", blocketSearchQuery: "mobil whiteboard hjul", traderaSearchQuery: "whiteboard mobil", displayOrder: 2 },

  // ---- dock-tb4 (3) ----
  { id: "dock-tb4-caldigit", itemId: "dock-tb4", name: "TS4 Thunderbolt 4 Dock", manufacturer: "CalDigit", sku: "TS4", imageUrl: "https://www.caldigit.com/wp-content/uploads/2022/06/TS4-Front.jpg", specs: { ports: "18 total, 98W charging", displays: "dual 4K@60 / single 8K", warranty: "2 years" }, priceNewSek: 4790, priceUsedDefaultSek: 2300, manufacturerUrl: "https://www.caldigit.com", blocketSearchQuery: "CalDigit TS4 docka", traderaSearchQuery: "CalDigit TS4", displayOrder: 0 },
  { id: "dock-tb4-anker-777", itemId: "dock-tb4", name: "777 Thunderbolt Dock", manufacturer: "Anker", sku: "777", imageUrl: "https://www.anker.com/cdn/shop/products/anker-777-thunderbolt-dock.jpg", specs: { ports: "12 total, 90W charging", displays: "dual 4K@60", warranty: "2 years" }, priceNewSek: 3590, priceUsedDefaultSek: 1700, manufacturerUrl: "https://www.anker.com", blocketSearchQuery: "Anker 777 docka", traderaSearchQuery: "Anker 777", displayOrder: 1 },
  { id: "dock-tb4-dell-wd22tb4", itemId: "dock-tb4", name: "WD22TB4 Thunderbolt Dock", manufacturer: "Dell", sku: "WD22TB4", imageUrl: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/docking-stations/wd22tb4/wd22tb4-cnb-00055-bk-1.jpg", specs: { ports: "14 total, 90W charging", displays: "dual 4K@60 / single 8K", warranty: "3 years" }, priceNewSek: 3290, priceUsedDefaultSek: 1500, manufacturerUrl: "https://www.dell.com", blocketSearchQuery: "Dell WD22TB4 docka", traderaSearchQuery: "Dell WD22", displayOrder: 2 },
];
