// Phase 8: product variants for the buyer to choose from.
//
// Image hosting: Unsplash CDN URLs (https://images.unsplash.com/...). Per Unsplash's
// license, images are free for commercial and non-commercial use. Attribution is not
// required but appreciated — credits are listed in comments per photo. If a brand
// objects to a representative photo being shown next to their product name, swap to
// a generic photo or remove that variant.
//
// Prices are in SEK (converted to öre at seed time, ×100).

export interface SeedVariant {
  id: string;                           // human-readable slug for the variant
  itemId: string;                       // FK to ItemCatalog.id
  name: string;
  manufacturer: string;
  sku?: string;
  imageUrl: string;
  specs: Record<string, string>;
  priceNewSek: number;
  priceUsedDefaultSek?: number;
  manufacturerUrl?: string;
  blocketSearchQuery?: string;
  traderaSearchQuery?: string;
  displayOrder: number;
}

const U = (id: string) => `https://images.unsplash.com/${id}?w=600&q=80&auto=format&fit=crop`;

export const VARIANTS: SeedVariant[] = [
  // ---- desk-electric (4) ----
  // Photo by @leonseibert on Unsplash
  { id: "desk-electric-kinnarps-oberon", itemId: "desk-electric", name: "Oberon sit-stand desk", manufacturer: "Kinnarps", sku: "OBERON-160", imageUrl: U("photo-1505691938895-1758d7feb511"), specs: { size: "160×80 cm", height: "65-130 cm", memory: "4 positions", finish: "Oak laminate" }, priceNewSek: 7200, priceUsedDefaultSek: 3400, manufacturerUrl: "https://www.kinnarps.com", blocketSearchQuery: "Kinnarps Oberon sit-stand 160", traderaSearchQuery: "Kinnarps Oberon hojhojsbord", displayOrder: 0 },
  // Photo by @rohitfarmer on Unsplash
  { id: "desk-electric-ikea-bekant", itemId: "desk-electric", name: "Bekant sit-stand desk", manufacturer: "IKEA Business", sku: "BEKANT-160", imageUrl: U("photo-1593062096033-9a26b09da705"), specs: { size: "160×80 cm", height: "65-125 cm", memory: "none", finish: "White" }, priceNewSek: 4900, priceUsedDefaultSek: 2200, manufacturerUrl: "https://www.ikea.com/se/sv", blocketSearchQuery: "IKEA Bekant 160 hojhojsbord", traderaSearchQuery: "IKEA Bekant hojhojsbord", displayOrder: 1 },
  // Photo by @bavi3 on Unsplash
  { id: "desk-electric-flexispot-e7", itemId: "desk-electric", name: "E7 sit-stand desk", manufacturer: "FlexiSpot", sku: "E7-160", imageUrl: U("photo-1545239351-1141bd82e8a6"), specs: { size: "160×80 cm", height: "60-125 cm", memory: "4 positions", finish: "Bamboo" }, priceNewSek: 5800, priceUsedDefaultSek: 2900, manufacturerUrl: "https://flexispot.se", blocketSearchQuery: "FlexiSpot E7 hojhojsbord", traderaSearchQuery: "FlexiSpot hojhojsbord", displayOrder: 2 },
  // Photo by @hugobarbosa on Unsplash
  { id: "desk-electric-uplift-v2", itemId: "desk-electric", name: "V2 sit-stand desk", manufacturer: "UPLIFT", sku: "UPLIFT-V2-72", imageUrl: U("photo-1518770660439-4636190af475"), specs: { size: "180×75 cm", height: "65-130 cm", memory: "4 positions", finish: "Walnut" }, priceNewSek: 9800, priceUsedDefaultSek: 4900, manufacturerUrl: "https://upliftdesk.com", blocketSearchQuery: "UPLIFT V2 hojhojsbord", traderaSearchQuery: "UPLIFT skrivbord", displayOrder: 3 },

  // ---- task-chair (4) ----
  // Photo by @hutomoabrianto on Unsplash
  { id: "task-chair-rh-logic", itemId: "task-chair", name: "Logic 400", manufacturer: "RH", sku: "RH-LOGIC-400", imageUrl: U("photo-1580480055273-228ff5388ef8"), specs: { recline: "synchron tilt", lumbar: "adjustable", armrests: "4D", warranty: "10 years" }, priceNewSek: 8500, priceUsedDefaultSek: 3800, manufacturerUrl: "https://www.rh.se", blocketSearchQuery: "RH Logic 400 kontorsstol", traderaSearchQuery: "RH Logic kontorsstol", displayOrder: 0 },
  // Photo by @maxchen2k on Unsplash
  { id: "task-chair-aeron", itemId: "task-chair", name: "Aeron Chair (size B)", manufacturer: "Herman Miller", sku: "AERON-B", imageUrl: U("photo-1592078615290-033ee584e267"), specs: { recline: "tilt limiter", lumbar: "PostureFit", armrests: "4D adjustable", warranty: "12 years" }, priceNewSek: 18500, priceUsedDefaultSek: 7900, manufacturerUrl: "https://www.hermanmiller.com", blocketSearchQuery: "Herman Miller Aeron storlek B", traderaSearchQuery: "Herman Miller Aeron", displayOrder: 1 },
  // Photo by @anniespratt on Unsplash
  { id: "task-chair-markus", itemId: "task-chair", name: "Markus", manufacturer: "IKEA", sku: "MARKUS", imageUrl: U("photo-1503602642458-232111445657"), specs: { recline: "tilt", lumbar: "fixed", armrests: "fixed", warranty: "10 years" }, priceNewSek: 2495, priceUsedDefaultSek: 990, manufacturerUrl: "https://www.ikea.com/se/sv/p/markus-kontorsstol-vissle-moerkgraa-70261150/", blocketSearchQuery: "IKEA Markus kontorsstol", traderaSearchQuery: "IKEA Markus stol", displayOrder: 2 },
  // Photo by @marvelous on Unsplash
  { id: "task-chair-steelcase-leap", itemId: "task-chair", name: "Leap V2", manufacturer: "Steelcase", sku: "LEAP-V2", imageUrl: U("photo-1505843490578-27a9c7e57b6d"), specs: { recline: "LiveBack", lumbar: "adjustable", armrests: "4D", warranty: "12 years" }, priceNewSek: 14500, priceUsedDefaultSek: 5500, manufacturerUrl: "https://www.steelcase.com", blocketSearchQuery: "Steelcase Leap V2", traderaSearchQuery: "Steelcase Leap", displayOrder: 3 },

  // ---- monitor-27 (4) ----
  { id: "monitor-27-dell-u2723qe", itemId: "monitor-27", name: 'UltraSharp 27" 4K U2723QE', manufacturer: "Dell", sku: "U2723QE", imageUrl: U("photo-1527443224154-c4a3942d3acf"), specs: { resolution: "3840×2160", panel: "IPS Black", refresh: "60 Hz", ports: "USB-C 90W, DP, HDMI" }, priceNewSek: 6900, priceUsedDefaultSek: 3200, manufacturerUrl: "https://www.dell.com", blocketSearchQuery: "Dell UltraSharp U2723QE", traderaSearchQuery: "Dell U2723QE", displayOrder: 0 },
  { id: "monitor-27-lg-27up850", itemId: "monitor-27", name: '27" UHD 27UP850N-W', manufacturer: "LG", sku: "27UP850N-W", imageUrl: U("photo-1547119957-637f8679db1e"), specs: { resolution: "3840×2160", panel: "IPS", refresh: "60 Hz", ports: "USB-C 96W, DP, 2× HDMI" }, priceNewSek: 5900, priceUsedDefaultSek: 2800, manufacturerUrl: "https://www.lg.com/se", blocketSearchQuery: "LG 27UP850 27 4K", traderaSearchQuery: "LG 27UP850", displayOrder: 1 },
  { id: "monitor-27-benq-pd2700u", itemId: "monitor-27", name: 'DesignVue PD2700U', manufacturer: "BenQ", sku: "PD2700U", imageUrl: U("photo-1496181133206-80ce9b88a853"), specs: { resolution: "3840×2160", panel: "IPS", refresh: "60 Hz", ports: "DP, 2× HDMI, USB-A hub" }, priceNewSek: 7200, priceUsedDefaultSek: 3400, manufacturerUrl: "https://www.benq.eu", blocketSearchQuery: "BenQ PD2700U 27", traderaSearchQuery: "BenQ PD2700U", displayOrder: 2 },
  { id: "monitor-27-samsung-s27a800", itemId: "monitor-27", name: 'ViewFinity S8 S27A800UJN', manufacturer: "Samsung", sku: "S27A800UJN", imageUrl: U("photo-1593640408182-31c70c8268f5"), specs: { resolution: "3840×2160", panel: "IPS", refresh: "60 Hz", ports: "USB-C 90W, DP, HDMI" }, priceNewSek: 5400, priceUsedDefaultSek: 2500, manufacturerUrl: "https://www.samsung.com/se", blocketSearchQuery: "Samsung S27A800 27 4K", traderaSearchQuery: "Samsung ViewFinity", displayOrder: 3 },

  // ---- monitor-arm (3) ----
  { id: "monitor-arm-ergotron-lx", itemId: "monitor-arm", name: "LX Desk Mount LCD Arm", manufacturer: "Ergotron", sku: "LX-DESK", imageUrl: U("photo-1518770660439-4636190af475"), specs: { mount: "VESA 75/100", capacity: "up to 11.3 kg", motion: "tilt, pan, rotate" }, priceNewSek: 2400, priceUsedDefaultSek: 1100, manufacturerUrl: "https://www.ergotron.com", blocketSearchQuery: "Ergotron LX skarmarm", traderaSearchQuery: "Ergotron LX", displayOrder: 0 },
  { id: "monitor-arm-humanscale-m8", itemId: "monitor-arm", name: "M8.1 Monitor Arm", manufacturer: "Humanscale", sku: "M8.1", imageUrl: U("photo-1593062096033-9a26b09da705"), specs: { mount: "VESA 75/100", capacity: "up to 13 kg", motion: "weightless counterbalance" }, priceNewSek: 4200, priceUsedDefaultSek: 2000, manufacturerUrl: "https://www.humanscale.com", blocketSearchQuery: "Humanscale M8 skarmarm", traderaSearchQuery: "Humanscale M8", displayOrder: 1 },
  { id: "monitor-arm-ikea-elloven", itemId: "monitor-arm", name: "Elloven", manufacturer: "IKEA", sku: "ELLOVEN", imageUrl: U("photo-1504805572947-34fad45aed93"), specs: { mount: "VESA 100", capacity: "up to 8 kg", motion: "tilt, swivel" }, priceNewSek: 599, priceUsedDefaultSek: 250, manufacturerUrl: "https://www.ikea.com/se/sv", blocketSearchQuery: "IKEA Elloven skarmarm", traderaSearchQuery: "IKEA Elloven", displayOrder: 2 },

  // ---- headset (3) ----
  { id: "headset-jabra-evolve2-65", itemId: "headset", name: "Evolve2 65 USB-C UC", manufacturer: "Jabra", sku: "EVOLVE2-65-USC", imageUrl: U("photo-1505740420928-5e560c06d30e"), specs: { wireless: "Bluetooth 5.0", battery: "37h talk", noise: "ANC", certs: "Teams/Zoom" }, priceNewSek: 2890, priceUsedDefaultSek: 1300, manufacturerUrl: "https://www.jabra.se", blocketSearchQuery: "Jabra Evolve2 65", traderaSearchQuery: "Jabra Evolve2", displayOrder: 0 },
  { id: "headset-logitech-zone-vibe", itemId: "headset", name: "Zone Vibe 125", manufacturer: "Logitech", sku: "ZONE-VIBE-125", imageUrl: U("photo-1583394838336-acd977736f90"), specs: { wireless: "Bluetooth", battery: "18h", noise: "noise-cancelling mic", certs: "Teams" }, priceNewSek: 1190, priceUsedDefaultSek: 550, manufacturerUrl: "https://www.logitech.com/sv-se", blocketSearchQuery: "Logitech Zone Vibe 125", traderaSearchQuery: "Logitech Zone", displayOrder: 1 },
  { id: "headset-poly-voyager-focus2", itemId: "headset", name: "Voyager Focus 2", manufacturer: "Poly (HP)", sku: "VOYAGER-FOCUS-2", imageUrl: U("photo-1546435770-a3e426bf472b"), specs: { wireless: "Bluetooth 5.1", battery: "19h talk", noise: "ANC", certs: "Teams/Zoom" }, priceNewSek: 2790, priceUsedDefaultSek: 1300, manufacturerUrl: "https://www.poly.com", blocketSearchQuery: "Poly Voyager Focus 2", traderaSearchQuery: "Poly Voyager", displayOrder: 2 },

  // ---- meeting-table-6 (3) ----
  { id: "meeting-table-6-vitra-em", itemId: "meeting-table-6", name: "EM Table 200×100", manufacturer: "Vitra", sku: "EM-200", imageUrl: U("photo-1577412647305-991150c7d163"), specs: { size: "200×100 cm", finish: "Solid oak", base: "Black powder-coated steel" }, priceNewSek: 18000, priceUsedDefaultSek: 8500, manufacturerUrl: "https://www.vitra.com", blocketSearchQuery: "Vitra EM Table mötesbord", traderaSearchQuery: "Vitra EM Table", displayOrder: 0 },
  { id: "meeting-table-6-string", itemId: "meeting-table-6", name: "Bordsskiva ek 200×100", manufacturer: "String Furniture", sku: "STR-200", imageUrl: U("photo-1497366811353-6870744d04b2"), specs: { size: "200×100 cm", finish: "Oak veneer", base: "Anthracite frame" }, priceNewSek: 9500, priceUsedDefaultSek: 4500, manufacturerUrl: "https://stringfurniture.com", blocketSearchQuery: "String mötesbord 200", traderaSearchQuery: "String bord 200", displayOrder: 1 },
  { id: "meeting-table-6-ikea-mittzon", itemId: "meeting-table-6", name: "Mittzon 200×100", manufacturer: "IKEA Business", sku: "MITTZON-200", imageUrl: U("photo-1577412647305-991150c7d163"), specs: { size: "200×100 cm", finish: "White or oak", base: "Steel" }, priceNewSek: 6900, priceUsedDefaultSek: 3000, manufacturerUrl: "https://www.ikea.com/se/sv/cat/mittzon", blocketSearchQuery: "IKEA Mittzon mötesbord", traderaSearchQuery: "IKEA Mittzon", displayOrder: 2 },

  // ---- phone-booth (3) ----
  { id: "phone-booth-framery-one", itemId: "phone-booth", name: "Framery One", manufacturer: "Framery", sku: "FRAMERY-ONE", imageUrl: U("photo-1497366811353-6870744d04b2"), specs: { capacity: "1 person", ventilation: "active, sensor-triggered", acoustics: "−30 dB", dimensions: "100×90×223 cm" }, priceNewSek: 65000, priceUsedDefaultSek: 28000, manufacturerUrl: "https://frameryacoustics.com", blocketSearchQuery: "Framery One telefonbås", traderaSearchQuery: "Framery telefonbås", displayOrder: 0 },
  { id: "phone-booth-loop-mini", itemId: "phone-booth", name: "Mini Pod", manufacturer: "Loop Phone Booths", sku: "LOOP-MINI", imageUrl: U("photo-1497366754035-f200968a6e72"), specs: { capacity: "1 person", ventilation: "passive + USB fan", acoustics: "−25 dB", dimensions: "90×90×210 cm" }, priceNewSek: 38000, priceUsedDefaultSek: 18000, manufacturerUrl: "https://loopphonebooths.com", blocketSearchQuery: "Loop telefonbås", traderaSearchQuery: "Loop telefonbås", displayOrder: 1 },
  { id: "phone-booth-zenbooth-solo", itemId: "phone-booth", name: "Solo", manufacturer: "Zenbooth", sku: "SOLO", imageUrl: U("photo-1517502884422-41eaead166d4"), specs: { capacity: "1 person", ventilation: "active", acoustics: "−28 dB", dimensions: "97×97×218 cm" }, priceNewSek: 52000, priceUsedDefaultSek: 24000, manufacturerUrl: "https://zenbooth.net", blocketSearchQuery: "Zenbooth Solo telefonbås", traderaSearchQuery: "Zenbooth", displayOrder: 2 },

  // ---- coffee-machine (3) ----
  { id: "coffee-jura-x8", itemId: "coffee-machine", name: "X8", manufacturer: "Jura", sku: "JURA-X8", imageUrl: U("photo-1495474472287-4d71bcdd2085"), specs: { type: "fully automatic", capacity: "30+ cups/day", milk: "automatic frother" }, priceNewSek: 38000, priceUsedDefaultSek: 16000, manufacturerUrl: "https://se.jura.com", blocketSearchQuery: "Jura X8 espressomaskin", traderaSearchQuery: "Jura X8", displayOrder: 0 },
  { id: "coffee-wmf-9000s", itemId: "coffee-machine", name: "9000 S+", manufacturer: "WMF", sku: "WMF-9000S", imageUrl: U("photo-1509042239860-f550ce710b93"), specs: { type: "fully automatic", capacity: "150+ cups/day", milk: "twin steam" }, priceNewSek: 95000, priceUsedDefaultSek: 45000, manufacturerUrl: "https://www.wmf-coffeemachines.com", blocketSearchQuery: "WMF 9000 kaffemaskin", traderaSearchQuery: "WMF 9000", displayOrder: 1 },
  { id: "coffee-sage-barista-pro", itemId: "coffee-machine", name: "Barista Pro", manufacturer: "Sage", sku: "SES878", imageUrl: U("photo-1517701604599-bb29b565090c"), specs: { type: "semi-automatic", capacity: "20 cups/day", milk: "steam wand" }, priceNewSek: 11900, priceUsedDefaultSek: 5500, manufacturerUrl: "https://www.sageappliances.com", blocketSearchQuery: "Sage Barista Pro", traderaSearchQuery: "Sage Barista Pro", displayOrder: 2 },

  // ---- sofa-3 (3) ----
  { id: "sofa-3-vimle", itemId: "sofa-3", name: "Vimle 3-seat", manufacturer: "IKEA", sku: "VIMLE-3", imageUrl: U("photo-1555041469-a586c61ea9bc"), specs: { material: "Gunnared beige fabric", washable: "covers removable", warranty: "10 years" }, priceNewSek: 7995, priceUsedDefaultSek: 3500, manufacturerUrl: "https://www.ikea.com/se/sv/cat/vimle", blocketSearchQuery: "IKEA Vimle 3-sits soffa", traderaSearchQuery: "IKEA Vimle", displayOrder: 0 },
  { id: "sofa-3-stockholm", itemId: "sofa-3", name: "Stockholm 3-seat leather", manufacturer: "IKEA", sku: "STOCKHOLM-3-LTH", imageUrl: U("photo-1493663284031-b7e3aefcae8e"), specs: { material: "Grann nature leather", warranty: "10 years" }, priceNewSek: 15995, priceUsedDefaultSek: 7000, manufacturerUrl: "https://www.ikea.com/se/sv/cat/stockholm", blocketSearchQuery: "IKEA Stockholm soffa läder", traderaSearchQuery: "IKEA Stockholm soffa", displayOrder: 1 },
  { id: "sofa-3-svenssons", itemId: "sofa-3", name: "Borås 3-seat", manufacturer: "Svenssons", sku: "BORAS-3", imageUrl: U("photo-1540574163026-643ea20ade25"), specs: { material: "Velvet, multiple colours", warranty: "5 years" }, priceNewSek: 12500, priceUsedDefaultSek: 5500, manufacturerUrl: "https://www.svenssons.se", blocketSearchQuery: "Borås 3-sits soffa", traderaSearchQuery: "soffa 3-sits", displayOrder: 2 },

  // ---- armchair (3) ----
  { id: "armchair-strandmon", itemId: "armchair", name: "Strandmon Wing Chair", manufacturer: "IKEA", sku: "STRANDMON", imageUrl: U("photo-1567538096630-e0c55bd6374c"), specs: { style: "wing chair", material: "Skiftebo dark blue", warranty: "10 years" }, priceNewSek: 4495, priceUsedDefaultSek: 2000, manufacturerUrl: "https://www.ikea.com/se/sv/cat/strandmon", blocketSearchQuery: "IKEA Strandmon fåtölj", traderaSearchQuery: "Strandmon fåtölj", displayOrder: 0 },
  { id: "armchair-eames-lounge", itemId: "armchair", name: "Eames Lounge Chair", manufacturer: "Herman Miller / Vitra", sku: "EAMES-LOUNGE", imageUrl: U("photo-1506439773649-6e0eb8cfb237"), specs: { style: "iconic lounge", material: "Palisander + black leather", warranty: "30 years frame" }, priceNewSek: 78000, priceUsedDefaultSek: 38000, manufacturerUrl: "https://www.vitra.com", blocketSearchQuery: "Eames Lounge Chair Vitra", traderaSearchQuery: "Eames Lounge", displayOrder: 1 },
  { id: "armchair-poaeng", itemId: "armchair", name: "Poäng", manufacturer: "IKEA", sku: "POAEG", imageUrl: U("photo-1567538096621-38d2284b23ff"), specs: { style: "bent birch frame", material: "Hillared anthracite", warranty: "10 years" }, priceNewSek: 1495, priceUsedDefaultSek: 650, manufacturerUrl: "https://www.ikea.com/se/sv/cat/poaeg", blocketSearchQuery: "IKEA Poäng fåtölj", traderaSearchQuery: "IKEA Poäng", displayOrder: 2 },

  // ---- locker-8 (3) ----
  { id: "locker-8-bisley", itemId: "locker-8", name: "MultiDrawer 8-locker steel", manufacturer: "Bisley", sku: "BISLEY-8", imageUrl: U("photo-1631889993959-41b4e9c6e3c5"), specs: { compartments: "8", locks: "key per compartment", finish: "Slate gray" }, priceNewSek: 7200, priceUsedDefaultSek: 3200, manufacturerUrl: "https://bisley.com", blocketSearchQuery: "Bisley 8 fack stållskåp", traderaSearchQuery: "Bisley", displayOrder: 0 },
  { id: "locker-8-trippstadius", itemId: "locker-8", name: "TS8 lockers", manufacturer: "Tripps & Stadius", sku: "TS8", imageUrl: U("photo-1493663284031-b7e3aefcae8e"), specs: { compartments: "8", locks: "digital or key", finish: "Powder coat, RAL options" }, priceNewSek: 8400, priceUsedDefaultSek: 3700, manufacturerUrl: "#", blocketSearchQuery: "kontorsskap 8 fack", traderaSearchQuery: "kontorsskap låsbart", displayOrder: 1 },
  { id: "locker-8-ikea-trotten", itemId: "locker-8", name: "Trotten 8-compartment", manufacturer: "IKEA Business", sku: "TROTTEN-8", imageUrl: U("photo-1605557462898-e34b7b46f6dc"), specs: { compartments: "8", locks: "key per compartment", finish: "Anthracite" }, priceNewSek: 4995, priceUsedDefaultSek: 2200, manufacturerUrl: "https://www.ikea.com/se/sv", blocketSearchQuery: "IKEA Trotten 8 fack", traderaSearchQuery: "IKEA Trotten", displayOrder: 2 },

  // ---- whiteboard (3) ----
  { id: "whiteboard-lintex", itemId: "whiteboard", name: "Air Whiteboard 200×100", manufacturer: "Lintex", sku: "LINTEX-AIR-200", imageUrl: U("photo-1497366216548-37526070297c"), specs: { size: "200×100 cm", surface: "enamel", magnetic: "yes" }, priceNewSek: 3200, priceUsedDefaultSek: 1400, manufacturerUrl: "https://lintex.com", blocketSearchQuery: "Lintex whiteboard 200", traderaSearchQuery: "Lintex whiteboard", displayOrder: 0 },
  { id: "whiteboard-naga", itemId: "whiteboard", name: "Classic Whiteboard 200×100", manufacturer: "NAGA", sku: "NAGA-200", imageUrl: U("photo-1568952433726-3896e3881c65"), specs: { size: "200×100 cm", surface: "lacquered steel", magnetic: "yes" }, priceNewSek: 1990, priceUsedDefaultSek: 800, manufacturerUrl: "https://naga.dk", blocketSearchQuery: "NAGA whiteboard 200", traderaSearchQuery: "whiteboard 200", displayOrder: 1 },
  { id: "whiteboard-rocada-mobile", itemId: "whiteboard", name: "Mobile whiteboard 200×100", manufacturer: "Rocada", sku: "RD-MOBILE-200", imageUrl: U("photo-1581368135153-a506cf13b1e1"), specs: { size: "200×100 cm", surface: "magnetic enamel", mobile: "wheels, double-sided" }, priceNewSek: 4500, priceUsedDefaultSek: 1900, manufacturerUrl: "https://rocada.es", blocketSearchQuery: "mobil whiteboard hjul", traderaSearchQuery: "whiteboard mobil", displayOrder: 2 },

  // ---- dock-tb4 (3) ----
  { id: "dock-tb4-caldigit", itemId: "dock-tb4", name: "TS4 Thunderbolt 4 Dock", manufacturer: "CalDigit", sku: "TS4", imageUrl: U("photo-1588339650988-5cefb6b25e72"), specs: { ports: "18 total, 98W charging", displays: "dual 4K@60 / single 8K", warranty: "2 years" }, priceNewSek: 4790, priceUsedDefaultSek: 2300, manufacturerUrl: "https://www.caldigit.com", blocketSearchQuery: "CalDigit TS4 docka", traderaSearchQuery: "CalDigit TS4", displayOrder: 0 },
  { id: "dock-tb4-anker-777", itemId: "dock-tb4", name: "777 Thunderbolt Dock", manufacturer: "Anker", sku: "777", imageUrl: U("photo-1591492654773-ba6dc1d52a78"), specs: { ports: "12 total, 90W charging", displays: "dual 4K@60", warranty: "2 years" }, priceNewSek: 3590, priceUsedDefaultSek: 1700, manufacturerUrl: "https://www.anker.com", blocketSearchQuery: "Anker 777 docka", traderaSearchQuery: "Anker 777", displayOrder: 1 },
  { id: "dock-tb4-dell-wd22tb4", itemId: "dock-tb4", name: "WD22TB4 Thunderbolt Dock", manufacturer: "Dell", sku: "WD22TB4", imageUrl: U("photo-1591488458180-6a8d2b30c5d4"), specs: { ports: "14 total, 90W charging", displays: "dual 4K@60 / single 8K", warranty: "3 years" }, priceNewSek: 3290, priceUsedDefaultSek: 1500, manufacturerUrl: "https://www.dell.com", blocketSearchQuery: "Dell WD22TB4 docka", traderaSearchQuery: "Dell WD22", displayOrder: 2 },
];
