// Phase 8: product variants for the buyer to choose from.
//
// Image hosting: images are downloaded at seed time and served from /variants/<id>.jpg.
// Run `pnpm db:download-images` to fetch all images to public/variants/.
// The `sourceUrl` field is the original web URL used by the download script;
// `imageUrl` is the local path served by Next.js.
//
// Prices are in SEK (converted to öre at seed time, ×100).

export interface SeedVariant {
  id: string;                           // human-readable slug for the variant
  itemId: string;                       // FK to ItemCatalog.id
  name: string;
  manufacturer: string;
  sku?: string;
  imageUrl: string;
  sourceUrl?: string;                   // original web URL used by download script
  specs: Record<string, string>;
  priceNewSek: number;
  priceUsedDefaultSek?: number;
  manufacturerUrl?: string;
  blocketSearchQuery?: string;
  traderaSearchQuery?: string;
  displayOrder: number;
}

export const VARIANTS: SeedVariant[] = [
  { id: "desk-electric-kinnarps-oberon", itemId: "desk-electric", name: "Oberon sit-stand desk", manufacturer: "Kinnarps", sku: "OBERON-160", imageUrl: "/variants/desk-electric-kinnarps-oberon.jpg", sourceUrl: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=85&auto=format", specs: { size: "160×80 cm", height: "65-130 cm", memory: "4 positions", finish: "Oak laminate" }, priceNewSek: 7200, priceUsedDefaultSek: 3400, manufacturerUrl: "https://www.kinnarps.com", blocketSearchQuery: "Kinnarps Oberon sit-stand 160", traderaSearchQuery: "Kinnarps Oberon hojhojsbord", displayOrder: 0 },
  { id: "desk-electric-ikea-bekant", itemId: "desk-electric", name: "Bekant sit-stand desk", manufacturer: "IKEA Business", sku: "BEKANT-160", imageUrl: "/variants/desk-electric-ikea-bekant.jpg", sourceUrl: "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=800&q=85&auto=format", specs: { size: "160×80 cm", height: "65-125 cm", memory: "none", finish: "White" }, priceNewSek: 4900, priceUsedDefaultSek: 2200, manufacturerUrl: "https://www.ikea.com/se/sv", blocketSearchQuery: "IKEA Bekant 160 hojhojsbord", traderaSearchQuery: "IKEA Bekant hojhojsbord", displayOrder: 1 },
  { id: "desk-electric-flexispot-e7", itemId: "desk-electric", name: "E7 sit-stand desk", manufacturer: "FlexiSpot", sku: "E7-160", imageUrl: "/variants/desk-electric-flexispot-e7.jpg", sourceUrl: "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800&q=85&auto=format", specs: { size: "160×80 cm", height: "60-125 cm", memory: "4 positions", finish: "Bamboo" }, priceNewSek: 5800, priceUsedDefaultSek: 2900, manufacturerUrl: "https://flexispot.se", blocketSearchQuery: "FlexiSpot E7 hojhojsbord", traderaSearchQuery: "FlexiSpot hojhojsbord", displayOrder: 2 },
  { id: "desk-electric-uplift-v2", itemId: "desk-electric", name: "V2 sit-stand desk", manufacturer: "UPLIFT", sku: "UPLIFT-V2-72", imageUrl: "/variants/desk-electric-uplift-v2.jpg", sourceUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=85&auto=format", specs: { size: "180×75 cm", height: "65-130 cm", memory: "4 positions", finish: "Walnut" }, priceNewSek: 9800, priceUsedDefaultSek: 4900, manufacturerUrl: "https://upliftdesk.com", blocketSearchQuery: "UPLIFT V2 hojhojsbord", traderaSearchQuery: "UPLIFT skrivbord", displayOrder: 3 },

  { id: "task-chair-rh-logic", itemId: "task-chair", name: "Logic 400", manufacturer: "RH", sku: "RH-LOGIC-400", imageUrl: "/variants/task-chair-rh-logic.jpg", sourceUrl: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800&q=85&auto=format", specs: { recline: "synchron tilt", lumbar: "adjustable", armrests: "4D", warranty: "10 years" }, priceNewSek: 8500, priceUsedDefaultSek: 3800, manufacturerUrl: "https://www.rh.se", blocketSearchQuery: "RH Logic 400 kontorsstol", traderaSearchQuery: "RH Logic kontorsstol", displayOrder: 0 },
  { id: "task-chair-aeron", itemId: "task-chair", name: "Aeron Chair (size B)", manufacturer: "Herman Miller", sku: "AERON-B", imageUrl: "/variants/task-chair-aeron.jpg", sourceUrl: "https://images.unsplash.com/photo-1517164850305-99a3e65bb47e?w=800&q=85&auto=format", specs: { recline: "tilt limiter", lumbar: "PostureFit", armrests: "4D adjustable", warranty: "12 years" }, priceNewSek: 18500, priceUsedDefaultSek: 7900, manufacturerUrl: "https://www.hermanmiller.com", blocketSearchQuery: "Herman Miller Aeron storlek B", traderaSearchQuery: "Herman Miller Aeron", displayOrder: 1 },
  { id: "task-chair-markus", itemId: "task-chair", name: "Markus", manufacturer: "IKEA", sku: "MARKUS", imageUrl: "/variants/task-chair-markus.jpg", sourceUrl: "https://www.ikea.com/se/sv/images/products/markus-kontorsstol-vissle-moerkgraa__0724714_pe734597_s5.jpg", specs: { recline: "tilt", lumbar: "fixed", armrests: "fixed", warranty: "10 years" }, priceNewSek: 2495, priceUsedDefaultSek: 990, manufacturerUrl: "https://www.ikea.com/se/sv/p/markus-kontorsstol-vissle-moerkgraa-70261150/", blocketSearchQuery: "IKEA Markus kontorsstol", traderaSearchQuery: "IKEA Markus stol", displayOrder: 2 },
  { id: "task-chair-steelcase-leap", itemId: "task-chair", name: "Leap V2", manufacturer: "Steelcase", sku: "LEAP-V2", imageUrl: "/variants/task-chair-steelcase-leap.jpg", sourceUrl: "https://images.unsplash.com/photo-1542621334-a254cf47733d?w=800&q=85&auto=format", specs: { recline: "LiveBack", lumbar: "adjustable", armrests: "4D", warranty: "12 years" }, priceNewSek: 14500, priceUsedDefaultSek: 5500, manufacturerUrl: "https://www.steelcase.com", blocketSearchQuery: "Steelcase Leap V2", traderaSearchQuery: "Steelcase Leap", displayOrder: 3 },

  { id: "monitor-27-dell-u2723qe", itemId: "monitor-27", name: 'UltraSharp 27" 4K U2723QE', manufacturer: "Dell", sku: "U2723QE", imageUrl: "/variants/monitor-27-dell-u2723qe.jpg", sourceUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=85&auto=format", specs: { resolution: "3840×2160", panel: "IPS Black", refresh: "60 Hz", ports: "USB-C 90W, DP, HDMI" }, priceNewSek: 6900, priceUsedDefaultSek: 3200, manufacturerUrl: "https://www.dell.com", blocketSearchQuery: "Dell UltraSharp U2723QE", traderaSearchQuery: "Dell U2723QE", displayOrder: 0 },
  { id: "monitor-27-lg-27up850", itemId: "monitor-27", name: '27" UHD 27UP850N-W', manufacturer: "LG", sku: "27UP850N-W", imageUrl: "/variants/monitor-27-lg-27up850.jpg", sourceUrl: "https://images.unsplash.com/photo-1547119957-637f8679db1e?w=800&q=85&auto=format", specs: { resolution: "3840×2160", panel: "IPS", refresh: "60 Hz", ports: "USB-C 96W, DP, 2× HDMI" }, priceNewSek: 5900, priceUsedDefaultSek: 2800, manufacturerUrl: "https://www.lg.com/se", blocketSearchQuery: "LG 27UP850 27 4K", traderaSearchQuery: "LG 27UP850", displayOrder: 1 },
  { id: "monitor-27-benq-pd2700u", itemId: "monitor-27", name: 'DesignVue PD2700U', manufacturer: "BenQ", sku: "PD2700U", imageUrl: "/variants/monitor-27-benq-pd2700u.jpg", sourceUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=85&auto=format", specs: { resolution: "3840×2160", panel: "IPS", refresh: "60 Hz", ports: "DP, 2× HDMI, USB-A hub" }, priceNewSek: 7200, priceUsedDefaultSek: 3400, manufacturerUrl: "https://www.benq.eu", blocketSearchQuery: "BenQ PD2700U 27", traderaSearchQuery: "BenQ PD2700U", displayOrder: 2 },
  { id: "monitor-27-samsung-s27a800", itemId: "monitor-27", name: 'ViewFinity S8 S27A800UJN', manufacturer: "Samsung", sku: "S27A800UJN", imageUrl: "/variants/monitor-27-samsung-s27a800.jpg", sourceUrl: "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&q=85&auto=format", specs: { resolution: "3840×2160", panel: "IPS", refresh: "60 Hz", ports: "USB-C 90W, DP, HDMI" }, priceNewSek: 5400, priceUsedDefaultSek: 2500, manufacturerUrl: "https://www.samsung.com/se", blocketSearchQuery: "Samsung S27A800 27 4K", traderaSearchQuery: "Samsung ViewFinity", displayOrder: 3 },

  { id: "monitor-arm-ergotron-lx", itemId: "monitor-arm", name: "LX Desk Mount LCD Arm", manufacturer: "Ergotron", sku: "LX-DESK", imageUrl: "/variants/monitor-arm-ergotron-lx.jpg", sourceUrl: "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800&q=85&auto=format", specs: { mount: "VESA 75/100", capacity: "up to 11.3 kg", motion: "tilt, pan, rotate" }, priceNewSek: 2400, priceUsedDefaultSek: 1100, manufacturerUrl: "https://www.ergotron.com", blocketSearchQuery: "Ergotron LX skarmarm", traderaSearchQuery: "Ergotron LX", displayOrder: 0 },
  { id: "monitor-arm-humanscale-m8", itemId: "monitor-arm", name: "M8.1 Monitor Arm", manufacturer: "Humanscale", sku: "M8.1", imageUrl: "/variants/monitor-arm-humanscale-m8.jpg", sourceUrl: "https://images.unsplash.com/photo-1620207418302-439b387441b0?w=800&q=85&auto=format", specs: { mount: "VESA 75/100", capacity: "up to 13 kg", motion: "weightless counterbalance" }, priceNewSek: 4200, priceUsedDefaultSek: 2000, manufacturerUrl: "https://www.humanscale.com", blocketSearchQuery: "Humanscale M8 skarmarm", traderaSearchQuery: "Humanscale M8", displayOrder: 1 },
  { id: "monitor-arm-ikea-elloven", itemId: "monitor-arm", name: "Elloven", manufacturer: "IKEA", sku: "ELLOVEN", imageUrl: "/variants/monitor-arm-ikea-elloven.jpg", sourceUrl: "https://images.unsplash.com/photo-1607435097405-db48f377bff6?w=800&q=85&auto=format", specs: { mount: "VESA 100", capacity: "up to 8 kg", motion: "tilt, swivel" }, priceNewSek: 599, priceUsedDefaultSek: 250, manufacturerUrl: "https://www.ikea.com/se/sv", blocketSearchQuery: "IKEA Elloven skarmarm", traderaSearchQuery: "IKEA Elloven", displayOrder: 2 },

  { id: "headset-jabra-evolve2-65", itemId: "headset", name: "Evolve2 65 USB-C UC", manufacturer: "Jabra", sku: "EVOLVE2-65-USC", imageUrl: "/variants/headset-jabra-evolve2-65.jpg", sourceUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=85&auto=format", specs: { wireless: "Bluetooth 5.0", battery: "37h talk", noise: "ANC", certs: "Teams/Zoom" }, priceNewSek: 2890, priceUsedDefaultSek: 1300, manufacturerUrl: "https://www.jabra.se", blocketSearchQuery: "Jabra Evolve2 65", traderaSearchQuery: "Jabra Evolve2", displayOrder: 0 },
  { id: "headset-logitech-zone-vibe", itemId: "headset", name: "Zone Vibe 125", manufacturer: "Logitech", sku: "ZONE-VIBE-125", imageUrl: "/variants/headset-logitech-zone-vibe.jpg", sourceUrl: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=85&auto=format", specs: { wireless: "Bluetooth", battery: "18h", noise: "noise-cancelling mic", certs: "Teams" }, priceNewSek: 1190, priceUsedDefaultSek: 550, manufacturerUrl: "https://www.logitech.com/sv-se", blocketSearchQuery: "Logitech Zone Vibe 125", traderaSearchQuery: "Logitech Zone", displayOrder: 1 },
  { id: "headset-poly-voyager-focus2", itemId: "headset", name: "Voyager Focus 2", manufacturer: "Poly (HP)", sku: "VOYAGER-FOCUS-2", imageUrl: "/variants/headset-poly-voyager-focus2.jpg", sourceUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=85&auto=format", specs: { wireless: "Bluetooth 5.1", battery: "19h talk", noise: "ANC", certs: "Teams/Zoom" }, priceNewSek: 2790, priceUsedDefaultSek: 1300, manufacturerUrl: "https://www.poly.com", blocketSearchQuery: "Poly Voyager Focus 2", traderaSearchQuery: "Poly Voyager", displayOrder: 2 },

  { id: "meeting-table-6-vitra-em", itemId: "meeting-table-6", name: "EM Table 200×100", manufacturer: "Vitra", sku: "EM-200", imageUrl: "/variants/meeting-table-6-vitra-em.jpg", sourceUrl: "https://images.unsplash.com/photo-1577412647305-991150c7d163?w=800&q=85&auto=format", specs: { size: "200×100 cm", finish: "Solid oak", base: "Black powder-coated steel" }, priceNewSek: 18000, priceUsedDefaultSek: 8500, manufacturerUrl: "https://www.vitra.com", blocketSearchQuery: "Vitra EM Table mötesbord", traderaSearchQuery: "Vitra EM Table", displayOrder: 0 },
  { id: "meeting-table-6-string", itemId: "meeting-table-6", name: "Bordsskiva ek 200×100", manufacturer: "String Furniture", sku: "STR-200", imageUrl: "/variants/meeting-table-6-string.jpg", sourceUrl: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=85&auto=format", specs: { size: "200×100 cm", finish: "Oak veneer", base: "Anthracite frame" }, priceNewSek: 9500, priceUsedDefaultSek: 4500, manufacturerUrl: "https://stringfurniture.com", blocketSearchQuery: "String mötesbord 200", traderaSearchQuery: "String bord 200", displayOrder: 1 },
  { id: "meeting-table-6-ikea-mittzon", itemId: "meeting-table-6", name: "Mittzon 200×100", manufacturer: "IKEA Business", sku: "MITTZON-200", imageUrl: "/variants/meeting-table-6-ikea-mittzon.jpg", sourceUrl: "https://images.unsplash.com/photo-1431540015161-0bf868a2d407?w=800&q=85&auto=format", specs: { size: "200×100 cm", finish: "White or oak", base: "Steel" }, priceNewSek: 6900, priceUsedDefaultSek: 3000, manufacturerUrl: "https://www.ikea.com/se/sv/cat/mittzon", blocketSearchQuery: "IKEA Mittzon mötesbord", traderaSearchQuery: "IKEA Mittzon", displayOrder: 2 },

  { id: "phone-booth-framery-one", itemId: "phone-booth", name: "Framery One", manufacturer: "Framery", sku: "FRAMERY-ONE", imageUrl: "/variants/phone-booth-framery-one.jpg", sourceUrl: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&q=85&auto=format", specs: { capacity: "1 person", ventilation: "active, sensor-triggered", acoustics: "−30 dB", dimensions: "100×90×223 cm" }, priceNewSek: 65000, priceUsedDefaultSek: 28000, manufacturerUrl: "https://frameryacoustics.com", blocketSearchQuery: "Framery One telefonbås", traderaSearchQuery: "Framery telefonbås", displayOrder: 0 },
  { id: "phone-booth-loop-mini", itemId: "phone-booth", name: "Mini Pod", manufacturer: "Loop Phone Booths", sku: "LOOP-MINI", imageUrl: "/variants/phone-booth-loop-mini.jpg", sourceUrl: "https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=800&q=85&auto=format", specs: { capacity: "1 person", ventilation: "passive + USB fan", acoustics: "−25 dB", dimensions: "90×90×210 cm" }, priceNewSek: 38000, priceUsedDefaultSek: 18000, manufacturerUrl: "https://loopphonebooths.com", blocketSearchQuery: "Loop telefonbås", traderaSearchQuery: "Loop telefonbås", displayOrder: 1 },
  { id: "phone-booth-zenbooth-solo", itemId: "phone-booth", name: "Solo", manufacturer: "Zenbooth", sku: "SOLO", imageUrl: "/variants/phone-booth-zenbooth-solo.jpg", sourceUrl: "https://images.unsplash.com/photo-1521737852567-6949f3f9f2b5?w=800&q=85&auto=format", specs: { capacity: "1 person", ventilation: "active", acoustics: "−28 dB", dimensions: "97×97×218 cm" }, priceNewSek: 52000, priceUsedDefaultSek: 24000, manufacturerUrl: "https://zenbooth.net", blocketSearchQuery: "Zenbooth Solo telefonbås", traderaSearchQuery: "Zenbooth", displayOrder: 2 },

  { id: "coffee-jura-x8", itemId: "coffee-machine", name: "X8", manufacturer: "Jura", sku: "JURA-X8", imageUrl: "/variants/coffee-jura-x8.jpg", sourceUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=85&auto=format", specs: { type: "fully automatic", capacity: "30+ cups/day", milk: "automatic frother" }, priceNewSek: 38000, priceUsedDefaultSek: 16000, manufacturerUrl: "https://se.jura.com", blocketSearchQuery: "Jura X8 espressomaskin", traderaSearchQuery: "Jura X8", displayOrder: 0 },
  { id: "coffee-wmf-9000s", itemId: "coffee-machine", name: "9000 S+", manufacturer: "WMF", sku: "WMF-9000S", imageUrl: "/variants/coffee-wmf-9000s.jpg", sourceUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=85&auto=format", specs: { type: "fully automatic", capacity: "150+ cups/day", milk: "twin steam" }, priceNewSek: 95000, priceUsedDefaultSek: 45000, manufacturerUrl: "https://www.wmf-coffeemachines.com", blocketSearchQuery: "WMF 9000 kaffemaskin", traderaSearchQuery: "WMF 9000", displayOrder: 1 },
  { id: "coffee-sage-barista-pro", itemId: "coffee-machine", name: "Barista Pro", manufacturer: "Sage", sku: "SES878", imageUrl: "/variants/coffee-sage-barista-pro.jpg", sourceUrl: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&q=85&auto=format", specs: { type: "semi-automatic", capacity: "20 cups/day", milk: "steam wand" }, priceNewSek: 11900, priceUsedDefaultSek: 5500, manufacturerUrl: "https://www.sageappliances.com", blocketSearchQuery: "Sage Barista Pro", traderaSearchQuery: "Sage Barista Pro", displayOrder: 2 },

  { id: "sofa-3-vimle", itemId: "sofa-3", name: "Vimle 3-seat", manufacturer: "IKEA", sku: "VIMLE-3", imageUrl: "/variants/sofa-3-vimle.jpg", sourceUrl: "https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=800&q=85&auto=format", specs: { material: "Gunnared beige fabric", washable: "covers removable", warranty: "10 years" }, priceNewSek: 7995, priceUsedDefaultSek: 3500, manufacturerUrl: "https://www.ikea.com/se/sv/cat/vimle", blocketSearchQuery: "IKEA Vimle 3-sits soffa", traderaSearchQuery: "IKEA Vimle", displayOrder: 0 },
  { id: "sofa-3-stockholm", itemId: "sofa-3", name: "Stockholm 3-seat leather", manufacturer: "IKEA", sku: "STOCKHOLM-3-LTH", imageUrl: "/variants/sofa-3-stockholm.jpg", sourceUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=85&auto=format", specs: { material: "Grann nature leather", warranty: "10 years" }, priceNewSek: 15995, priceUsedDefaultSek: 7000, manufacturerUrl: "https://www.ikea.com/se/sv/cat/stockholm", blocketSearchQuery: "IKEA Stockholm soffa läder", traderaSearchQuery: "IKEA Stockholm soffa", displayOrder: 1 },
  { id: "sofa-3-svenssons", itemId: "sofa-3", name: "Borås 3-seat", manufacturer: "Svenssons", sku: "BORAS-3", imageUrl: "/variants/sofa-3-svenssons.jpg", sourceUrl: "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=800&q=85&auto=format", specs: { material: "Velvet, multiple colours", warranty: "5 years" }, priceNewSek: 12500, priceUsedDefaultSek: 5500, manufacturerUrl: "https://www.svenssons.se", blocketSearchQuery: "Borås 3-sits soffa", traderaSearchQuery: "soffa 3-sits", displayOrder: 2 },

  { id: "armchair-strandmon", itemId: "armchair", name: "Strandmon Wing Chair", manufacturer: "IKEA", sku: "STRANDMON", imageUrl: "/variants/armchair-strandmon.jpg", sourceUrl: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=85&auto=format", specs: { style: "wing chair", material: "Skiftebo dark blue", warranty: "10 years" }, priceNewSek: 4495, priceUsedDefaultSek: 2000, manufacturerUrl: "https://www.ikea.com/se/sv/cat/strandmon", blocketSearchQuery: "IKEA Strandmon fåtölj", traderaSearchQuery: "Strandmon fåtölj", displayOrder: 0 },
  { id: "armchair-eames-lounge", itemId: "armchair", name: "Eames Lounge Chair", manufacturer: "Herman Miller / Vitra", sku: "EAMES-LOUNGE", imageUrl: "/variants/armchair-eames-lounge.jpg", sourceUrl: "https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=800&q=85&auto=format", specs: { style: "iconic lounge", material: "Palisander + black leather", warranty: "30 years frame" }, priceNewSek: 78000, priceUsedDefaultSek: 38000, manufacturerUrl: "https://www.vitra.com", blocketSearchQuery: "Eames Lounge Chair Vitra", traderaSearchQuery: "Eames Lounge", displayOrder: 1 },
  { id: "armchair-poaeng", itemId: "armchair", name: "Poäng", manufacturer: "IKEA", sku: "POAEG", imageUrl: "/variants/armchair-poaeng.jpg", sourceUrl: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=85&auto=format", specs: { style: "bent birch frame", material: "Hillared anthracite", warranty: "10 years" }, priceNewSek: 1495, priceUsedDefaultSek: 650, manufacturerUrl: "https://www.ikea.com/se/sv/cat/poaeg", blocketSearchQuery: "IKEA Poäng fåtölj", traderaSearchQuery: "IKEA Poäng", displayOrder: 2 },

  { id: "locker-8-bisley", itemId: "locker-8", name: "MultiDrawer 8-locker steel", manufacturer: "Bisley", sku: "BISLEY-8", imageUrl: "/variants/locker-8-bisley.jpg", sourceUrl: "https://images.unsplash.com/photo-1631889993959-41b4e9c6e3c5?w=800&q=85&auto=format", specs: { compartments: "8", locks: "key per compartment", finish: "Slate gray" }, priceNewSek: 7200, priceUsedDefaultSek: 3200, manufacturerUrl: "https://bisley.com", blocketSearchQuery: "Bisley 8 fack stållskåp", traderaSearchQuery: "Bisley", displayOrder: 0 },
  { id: "locker-8-trippstadius", itemId: "locker-8", name: "TS8 lockers", manufacturer: "Tripps & Stadius", sku: "TS8", imageUrl: "/variants/locker-8-trippstadius.jpg", sourceUrl: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=85&auto=format", specs: { compartments: "8", locks: "digital or key", finish: "Powder coat, RAL options" }, priceNewSek: 8400, priceUsedDefaultSek: 3700, manufacturerUrl: "#", blocketSearchQuery: "kontorsskap 8 fack", traderaSearchQuery: "kontorsskap låsbart", displayOrder: 1 },
  { id: "locker-8-ikea-trotten", itemId: "locker-8", name: "Trotten 8-compartment", manufacturer: "IKEA Business", sku: "TROTTEN-8", imageUrl: "/variants/locker-8-ikea-trotten.jpg", sourceUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=85&auto=format", specs: { compartments: "8", locks: "key per compartment", finish: "Anthracite" }, priceNewSek: 4995, priceUsedDefaultSek: 2200, manufacturerUrl: "https://www.ikea.com/se/sv", blocketSearchQuery: "IKEA Trotten 8 fack", traderaSearchQuery: "IKEA Trotten", displayOrder: 2 },

  { id: "whiteboard-lintex", itemId: "whiteboard", name: "Air Whiteboard 200×100", manufacturer: "Lintex", sku: "LINTEX-AIR-200", imageUrl: "/variants/whiteboard-lintex.jpg", sourceUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=85&auto=format", specs: { size: "200×100 cm", surface: "enamel", magnetic: "yes" }, priceNewSek: 3200, priceUsedDefaultSek: 1400, manufacturerUrl: "https://lintex.com", blocketSearchQuery: "Lintex whiteboard 200", traderaSearchQuery: "Lintex whiteboard", displayOrder: 0 },
  { id: "whiteboard-naga", itemId: "whiteboard", name: "Classic Whiteboard 200×100", manufacturer: "NAGA", sku: "NAGA-200", imageUrl: "/variants/whiteboard-naga.jpg", sourceUrl: "https://images.unsplash.com/photo-1568952433726-3896e3881c65?w=800&q=85&auto=format", specs: { size: "200×100 cm", surface: "lacquered steel", magnetic: "yes" }, priceNewSek: 1990, priceUsedDefaultSek: 800, manufacturerUrl: "https://naga.dk", blocketSearchQuery: "NAGA whiteboard 200", traderaSearchQuery: "whiteboard 200", displayOrder: 1 },
  { id: "whiteboard-rocada-mobile", itemId: "whiteboard", name: "Mobile whiteboard 200×100", manufacturer: "Rocada", sku: "RD-MOBILE-200", imageUrl: "/variants/whiteboard-rocada-mobile.jpg", sourceUrl: "https://images.unsplash.com/photo-1581368135153-a506cf13b1e1?w=800&q=85&auto=format", specs: { size: "200×100 cm", surface: "magnetic enamel", mobile: "wheels, double-sided" }, priceNewSek: 4500, priceUsedDefaultSek: 1900, manufacturerUrl: "https://rocada.es", blocketSearchQuery: "mobil whiteboard hjul", traderaSearchQuery: "whiteboard mobil", displayOrder: 2 },

  { id: "dock-tb4-caldigit", itemId: "dock-tb4", name: "TS4 Thunderbolt 4 Dock", manufacturer: "CalDigit", sku: "TS4", imageUrl: "/variants/dock-tb4-caldigit.jpg", sourceUrl: "https://images.unsplash.com/photo-1625948515291-69613efd103f?w=800&q=85&auto=format", specs: { ports: "18 total, 98W charging", displays: "dual 4K@60 / single 8K", warranty: "2 years" }, priceNewSek: 4790, priceUsedDefaultSek: 2300, manufacturerUrl: "https://www.caldigit.com", blocketSearchQuery: "CalDigit TS4 docka", traderaSearchQuery: "CalDigit TS4", displayOrder: 0 },
  { id: "dock-tb4-anker-777", itemId: "dock-tb4", name: "777 Thunderbolt Dock", manufacturer: "Anker", sku: "777", imageUrl: "/variants/dock-tb4-anker-777.jpg", sourceUrl: "https://images.unsplash.com/photo-1541558869434-2840d308329a?w=800&q=85&auto=format", specs: { ports: "12 total, 90W charging", displays: "dual 4K@60", warranty: "2 years" }, priceNewSek: 3590, priceUsedDefaultSek: 1700, manufacturerUrl: "https://www.anker.com", blocketSearchQuery: "Anker 777 docka", traderaSearchQuery: "Anker 777", displayOrder: 1 },
  { id: "dock-tb4-dell-wd22tb4", itemId: "dock-tb4", name: "WD22TB4 Thunderbolt Dock", manufacturer: "Dell", sku: "WD22TB4", imageUrl: "/variants/dock-tb4-dell-wd22tb4.jpg", sourceUrl: "https://images.unsplash.com/photo-1629131726692-1accd0c53ce0?w=800&q=85&auto=format", specs: { ports: "14 total, 90W charging", displays: "dual 4K@60 / single 8K", warranty: "3 years" }, priceNewSek: 3290, priceUsedDefaultSek: 1500, manufacturerUrl: "https://www.dell.com", blocketSearchQuery: "Dell WD22TB4 docka", traderaSearchQuery: "Dell WD22", displayOrder: 2 },

  // ── Phase 9 new variants ──

  // monitor-24 (24-inch FHD)
  { id: "monitor-24-dell-p2422h", itemId: "monitor-24", name: 'P2422H 24" FHD', manufacturer: "Dell", sku: "P2422H", imageUrl: "/variants/monitor-24-dell-p2422h.jpg", sourceUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=85&auto=format", specs: { resolution: "1920×1080", panel: "IPS", refresh: "60 Hz", ports: "DP, HDMI, VGA, USB hub" }, priceNewSek: 2490, priceUsedDefaultSek: 1100, manufacturerUrl: "https://www.dell.com", blocketSearchQuery: "Dell P2422H 24", traderaSearchQuery: "Dell P2422H", displayOrder: 0 },
  { id: "monitor-24-lg-24mp400", itemId: "monitor-24", name: '24MP400-B 24" FHD', manufacturer: "LG", sku: "24MP400-B", imageUrl: "/variants/monitor-24-lg-24mp400.jpg", sourceUrl: "https://images.unsplash.com/photo-1547119957-637f8679db1e?w=800&q=85&auto=format", specs: { resolution: "1920×1080", panel: "IPS", refresh: "75 Hz", ports: "HDMI, VGA" }, priceNewSek: 1690, priceUsedDefaultSek: 750, manufacturerUrl: "https://www.lg.com/se", blocketSearchQuery: "LG 24MP400 24", traderaSearchQuery: "LG 24 monitor", displayOrder: 1 },

  // monitor-32 (32-inch 4K)
  { id: "monitor-32-dell-u3223qe", itemId: "monitor-32", name: 'UltraSharp 32" 4K U3223QE', manufacturer: "Dell", sku: "U3223QE", imageUrl: "/variants/monitor-32-dell-u3223qe.jpg", sourceUrl: "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&q=85&auto=format", specs: { resolution: "3840×2160", panel: "IPS Black", refresh: "60 Hz", ports: "USB-C 90W, DP, HDMI" }, priceNewSek: 8900, priceUsedDefaultSek: 4200, manufacturerUrl: "https://www.dell.com", blocketSearchQuery: "Dell U3223QE 32 4K", traderaSearchQuery: "Dell U3223QE", displayOrder: 0 },
  { id: "monitor-32-lg-32up550n", itemId: "monitor-32", name: '32" UHD 32UP550N-W', manufacturer: "LG", sku: "32UP550N-W", imageUrl: "/variants/monitor-32-lg-32up550n.jpg", sourceUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=85&auto=format", specs: { resolution: "3840×2160", panel: "VA", refresh: "60 Hz", ports: "DP, 2× HDMI, USB-C" }, priceNewSek: 5990, priceUsedDefaultSek: 2800, manufacturerUrl: "https://www.lg.com/se", blocketSearchQuery: "LG 32UP550 32 4K", traderaSearchQuery: "LG 32 4K", displayOrder: 1 },

  // monitor-ultrawide (34-inch)
  { id: "monitor-ultrawide-dell-u3423we", itemId: "monitor-ultrawide", name: 'UltraSharp 34" U3423WE', manufacturer: "Dell", sku: "U3423WE", imageUrl: "/variants/monitor-ultrawide-dell-u3423we.jpg", sourceUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=85&auto=format", specs: { resolution: "3440×1440", panel: "IPS Black", refresh: "60 Hz", ports: "USB-C 90W, DP, HDMI" }, priceNewSek: 8990, priceUsedDefaultSek: 4200, manufacturerUrl: "https://www.dell.com", blocketSearchQuery: "Dell U3423 ultrawide", traderaSearchQuery: "Dell U3423", displayOrder: 0 },
  { id: "monitor-ultrawide-lg-34wp65c", itemId: "monitor-ultrawide", name: '34WP65C-B 34" UltraWide', manufacturer: "LG", sku: "34WP65C-B", imageUrl: "/variants/monitor-ultrawide-lg-34wp65c.jpg", sourceUrl: "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&q=85&auto=format", specs: { resolution: "3440×1440", panel: "VA curved", refresh: "160 Hz", ports: "DP, 2× HDMI, USB-C 90W" }, priceNewSek: 5490, priceUsedDefaultSek: 2600, manufacturerUrl: "https://www.lg.com/se", blocketSearchQuery: "LG 34WP65C ultrawide", traderaSearchQuery: "LG ultrawide", displayOrder: 1 },

  // monitor-curved-32
  { id: "monitor-curved-32-samsung-odyssey-g7", itemId: "monitor-curved-32", name: 'Odyssey G7 32" curved 4K', manufacturer: "Samsung", sku: "S32BG750NU", imageUrl: "/variants/monitor-curved-32-samsung-odyssey-g7.jpg", sourceUrl: "https://images.unsplash.com/photo-1547119957-637f8679db1e?w=800&q=85&auto=format", specs: { resolution: "3840×2160", panel: "VA 1000R curved", refresh: "144 Hz", ports: "DP, HDMI" }, priceNewSek: 9990, priceUsedDefaultSek: 4800, manufacturerUrl: "https://www.samsung.com/se", blocketSearchQuery: "Samsung Odyssey G7 32", traderaSearchQuery: "Samsung Odyssey", displayOrder: 0 },
  { id: "monitor-curved-32-msi-mag321cup", itemId: "monitor-curved-32", name: 'MAG 321CUP 32" curved 4K', manufacturer: "MSI", sku: "MAG321CUP", imageUrl: "/variants/monitor-curved-32-msi-mag321cup.jpg", sourceUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=85&auto=format", specs: { resolution: "3840×2160", panel: "VA 1500R curved", refresh: "160 Hz", ports: "DP, 2× HDMI" }, priceNewSek: 6990, priceUsedDefaultSek: 3300, manufacturerUrl: "https://www.msi.com", blocketSearchQuery: "MSI MAG321 32 curved", traderaSearchQuery: "MSI MAG321", displayOrder: 1 },

  // task-chair-budget
  // imageUrl = _placeholder.svg signals "no usable photo" → the UI shows a CatalogIcon instead of a wrong image (these two Unsplash IDs returned a yacht and architectural drawings).
  { id: "task-chair-budget-ikea-jarvfjallet", itemId: "task-chair-budget", name: "Järvfjället", manufacturer: "IKEA", sku: "JARVFJALLET", imageUrl: "/variants/_placeholder.svg", sourceUrl: "", specs: { recline: "tilt", lumbar: "adjustable", armrests: "adjustable", warranty: "10 years" }, priceNewSek: 2995, priceUsedDefaultSek: 1200, manufacturerUrl: "https://www.ikea.com/se/sv", blocketSearchQuery: "IKEA Järvfjället", traderaSearchQuery: "IKEA Järvfjället", displayOrder: 0 },
  { id: "task-chair-budget-hag-creed", itemId: "task-chair-budget", name: "HÅG Creed", manufacturer: "HÅG", sku: "HAG-CREED", imageUrl: "/variants/_placeholder.svg", sourceUrl: "", specs: { recline: "tilt", lumbar: "fixed", armrests: "adjustable", warranty: "10 years" }, priceNewSek: 2495, priceUsedDefaultSek: 1000, manufacturerUrl: "https://www.flokk.com/se/hag", blocketSearchQuery: "HÅG Creed kontorsstol", traderaSearchQuery: "HÅG Creed", displayOrder: 1 },

  // task-chair-premium
  { id: "task-chair-premium-aeron", itemId: "task-chair-premium", name: "Aeron (size B)", manufacturer: "Herman Miller", sku: "AERON-B", imageUrl: "/variants/task-chair-premium-aeron.jpg", sourceUrl: "https://images.unsplash.com/photo-1517164850305-99a3e65bb47e?w=800&q=85&auto=format", specs: { recline: "tilt limiter", lumbar: "PostureFit SL", armrests: "4D", warranty: "12 years" }, priceNewSek: 18500, priceUsedDefaultSek: 7900, manufacturerUrl: "https://www.hermanmiller.com", blocketSearchQuery: "Herman Miller Aeron storlek B", traderaSearchQuery: "Herman Miller Aeron", displayOrder: 0 },
  { id: "task-chair-premium-leap-v2", itemId: "task-chair-premium", name: "Leap V2", manufacturer: "Steelcase", sku: "LEAP-V2", imageUrl: "/variants/task-chair-premium-leap-v2.jpg", sourceUrl: "https://images.unsplash.com/photo-1542621334-a254cf47733d?w=800&q=85&auto=format", specs: { recline: "LiveBack", lumbar: "adjustable", armrests: "4D", warranty: "12 years" }, priceNewSek: 14500, priceUsedDefaultSek: 5500, manufacturerUrl: "https://www.steelcase.com", blocketSearchQuery: "Steelcase Leap V2", traderaSearchQuery: "Steelcase Leap", displayOrder: 1 },

  // desk-small (compact)
  { id: "desk-small-ikea-trotten-120", itemId: "desk-small", name: "Trotten 120×70 sit-stand", manufacturer: "IKEA Business", sku: "TROTTEN-120", imageUrl: "/variants/desk-small-ikea-trotten-120.jpg", sourceUrl: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=85&auto=format", specs: { size: "120×70 cm", height: "70-120 cm", memory: "none", finish: "Anthracite" }, priceNewSek: 3990, priceUsedDefaultSek: 1700, manufacturerUrl: "https://www.ikea.com/se/sv/cat/trotten", blocketSearchQuery: "IKEA Trotten 120", traderaSearchQuery: "IKEA Trotten", displayOrder: 0 },
  { id: "desk-small-flexispot-eg1", itemId: "desk-small", name: "EG1 compact sit-stand", manufacturer: "FlexiSpot", sku: "EG1-120", imageUrl: "/variants/desk-small-flexispot-eg1.jpg", sourceUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=85&auto=format", specs: { size: "120×60 cm", height: "70-118 cm", memory: "2 positions", finish: "White" }, priceNewSek: 3490, priceUsedDefaultSek: 1400, manufacturerUrl: "https://flexispot.se", blocketSearchQuery: "FlexiSpot EG1 120", traderaSearchQuery: "FlexiSpot kompakt", displayOrder: 1 },

  // desk-large (180×90)
  { id: "desk-large-kinnarps-oberon-180", itemId: "desk-large", name: "Oberon 180×90 sit-stand", manufacturer: "Kinnarps", sku: "OBERON-180", imageUrl: "/variants/desk-large-kinnarps-oberon-180.jpg", sourceUrl: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=85&auto=format", specs: { size: "180×90 cm", height: "65-130 cm", memory: "4 positions", finish: "Oak laminate" }, priceNewSek: 8400, priceUsedDefaultSek: 4000, manufacturerUrl: "https://www.kinnarps.com", blocketSearchQuery: "Kinnarps Oberon 180", traderaSearchQuery: "Kinnarps 180", displayOrder: 0 },
  { id: "desk-large-uplift-v2-180", itemId: "desk-large", name: "V2 180×75 sit-stand", manufacturer: "UPLIFT", sku: "UPLIFT-V2-180", imageUrl: "/variants/desk-large-uplift-v2-180.jpg", sourceUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=85&auto=format", specs: { size: "180×75 cm", height: "65-130 cm", memory: "4 positions", finish: "Walnut" }, priceNewSek: 7900, priceUsedDefaultSek: 3800, manufacturerUrl: "https://upliftdesk.com", blocketSearchQuery: "UPLIFT V2 180", traderaSearchQuery: "UPLIFT 180", displayOrder: 1 },

  // desk-l-shape
  { id: "desk-l-shape-flexispot-e7l", itemId: "desk-l-shape", name: "E7L L-shape sit-stand", manufacturer: "FlexiSpot", sku: "E7L", imageUrl: "/variants/desk-l-shape-flexispot-e7l.jpg", sourceUrl: "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800&q=85&auto=format", specs: { size: "180×160 cm corner", height: "60-125 cm", memory: "4 positions", finish: "Oak" }, priceNewSek: 11900, priceUsedDefaultSek: 5500, manufacturerUrl: "https://flexispot.se", blocketSearchQuery: "FlexiSpot E7L L-form", traderaSearchQuery: "FlexiSpot L-form", displayOrder: 0 },
  { id: "desk-l-shape-uplift-v2-l", itemId: "desk-l-shape", name: "V2 L-shape sit-stand", manufacturer: "UPLIFT", sku: "UPLIFT-V2-L", imageUrl: "/variants/desk-l-shape-uplift-v2-l.jpg", sourceUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=85&auto=format", specs: { size: "180×160 cm corner", height: "65-130 cm", memory: "4 positions", finish: "Walnut" }, priceNewSek: 13500, priceUsedDefaultSek: 6500, manufacturerUrl: "https://upliftdesk.com", blocketSearchQuery: "UPLIFT V2 L-form", traderaSearchQuery: "UPLIFT L-form", displayOrder: 1 },

  // headset-wired
  { id: "headset-wired-jabra-evolve-30", itemId: "headset-wired", name: "Evolve 30 II USB", manufacturer: "Jabra", sku: "EVOLVE-30-II", imageUrl: "/variants/headset-wired-jabra-evolve-30.jpg", sourceUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=85&auto=format", specs: { wired: "USB-A", noise: "passive noise cancellation", certs: "Teams/Zoom" }, priceNewSek: 1190, priceUsedDefaultSek: 500, manufacturerUrl: "https://www.jabra.se", blocketSearchQuery: "Jabra Evolve 30", traderaSearchQuery: "Jabra Evolve 30", displayOrder: 0 },
  { id: "headset-wired-plantronics-blackwire", itemId: "headset-wired", name: "Blackwire 3220 USB", manufacturer: "Poly (HP)", sku: "BLACKWIRE-3220", imageUrl: "/variants/headset-wired-plantronics-blackwire.jpg", sourceUrl: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=85&auto=format", specs: { wired: "USB-A + 3.5mm", noise: "noise-cancelling mic", certs: "Teams" }, priceNewSek: 690, priceUsedDefaultSek: 290, manufacturerUrl: "https://www.poly.com", blocketSearchQuery: "Plantronics Blackwire 3220", traderaSearchQuery: "Plantronics Blackwire", displayOrder: 1 },

  // headset-noise-cancel (premium ANC)
  { id: "headset-noise-cancel-bose-700-uc", itemId: "headset-noise-cancel", name: "700 UC", manufacturer: "Bose", sku: "BOSE-700-UC", imageUrl: "/variants/headset-noise-cancel-bose-700-uc.jpg", sourceUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=85&auto=format", specs: { wireless: "Bluetooth 5.0", battery: "20h talk", noise: "11-level ANC", certs: "Teams via dongle" }, priceNewSek: 5290, priceUsedDefaultSek: 2400, manufacturerUrl: "https://www.bose.com", blocketSearchQuery: "Bose 700 UC", traderaSearchQuery: "Bose 700", displayOrder: 0 },
  { id: "headset-noise-cancel-jabra-evolve2-85", itemId: "headset-noise-cancel", name: "Evolve2 85", manufacturer: "Jabra", sku: "EVOLVE2-85", imageUrl: "/variants/headset-noise-cancel-jabra-evolve2-85.jpg", sourceUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=85&auto=format", specs: { wireless: "Bluetooth 5.0", battery: "37h talk ANC on", noise: "premium ANC", certs: "Teams/Zoom" }, priceNewSek: 4490, priceUsedDefaultSek: 2000, manufacturerUrl: "https://www.jabra.se", blocketSearchQuery: "Jabra Evolve2 85", traderaSearchQuery: "Jabra Evolve2 85", displayOrder: 1 },

  // storage-cabinet (general purpose, non-locking)
  { id: "storage-cabinet-ikea-galant", itemId: "storage-cabinet", name: "Galant cabinet 80×120", manufacturer: "IKEA Business", sku: "GALANT-80-120", imageUrl: "/variants/storage-cabinet-ikea-galant.jpg", sourceUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=85&auto=format", specs: { dimensions: "80×45×120 cm", shelves: "3 adjustable", lock: "no", finish: "Oak veneer" }, priceNewSek: 3490, priceUsedDefaultSek: 1500, manufacturerUrl: "https://www.ikea.com/se/sv/cat/galant", blocketSearchQuery: "IKEA Galant skåp", traderaSearchQuery: "IKEA Galant skåp", displayOrder: 0 },
  { id: "storage-cabinet-bisley-essentials", itemId: "storage-cabinet", name: "Essentials cabinet 80×120", manufacturer: "Bisley", sku: "BIS-ESS-80-120", imageUrl: "/variants/storage-cabinet-bisley-essentials.jpg", sourceUrl: "https://images.unsplash.com/photo-1631889993959-41b4e9c6e3c5?w=800&q=85&auto=format", specs: { dimensions: "80×45×120 cm", shelves: "3 adjustable", lock: "no", finish: "Powder-coated steel" }, priceNewSek: 4290, priceUsedDefaultSek: 1900, manufacturerUrl: "https://bisley.com", blocketSearchQuery: "Bisley skåp", traderaSearchQuery: "Bisley", displayOrder: 1 },

  // storage-shelving (bookcase-style, open)
  { id: "storage-shelving-string-system", itemId: "storage-shelving", name: "String system shelving", manufacturer: "String Furniture", sku: "STR-SHELF-180", imageUrl: "/variants/storage-shelving-string-system.jpg", sourceUrl: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&q=85&auto=format", specs: { tiers: "5", dimensions: "180×80 cm", finish: "Oak / walnut", magnetic: "modular" }, priceNewSek: 6800, priceUsedDefaultSek: 3000, manufacturerUrl: "https://stringfurniture.com", blocketSearchQuery: "String hyllsystem", traderaSearchQuery: "String hylla", displayOrder: 0 },
  { id: "storage-shelving-ikea-billy", itemId: "storage-shelving", name: "Billy bookcase 80×202", manufacturer: "IKEA", sku: "BILLY-80-202", imageUrl: "/variants/storage-shelving-ikea-billy.jpg", sourceUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=85&auto=format", specs: { tiers: "6", dimensions: "80×28×202 cm", finish: "White or oak", warranty: "10 years" }, priceNewSek: 995, priceUsedDefaultSek: 400, manufacturerUrl: "https://www.ikea.com/se/sv/cat/billy", blocketSearchQuery: "IKEA Billy bokhylla", traderaSearchQuery: "IKEA Billy", displayOrder: 1 },
];
